<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.3.450">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Homework 4 - MATH 4322</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="homework4_4322s_files/libs/clipboard/clipboard.min.js"></script>
<script src="homework4_4322s_files/libs/quarto-html/quarto.js"></script>
<script src="homework4_4322s_files/libs/quarto-html/popper.min.js"></script>
<script src="homework4_4322s_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="homework4_4322s_files/libs/quarto-html/anchor.min.js"></script>
<link href="homework4_4322s_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="homework4_4322s_files/libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="homework4_4322s_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="homework4_4322s_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="homework4_4322s_files/libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">

  <script src="https://polyfill.io/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

</head>

<body class="fullcontent">

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">

<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Homework 4 - MATH 4322</h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  

</header>

<section id="instructions" class="level2">
<h2 class="anchored" data-anchor-id="instructions">Instructions</h2>
<ol type="1">
<li>Due date: March 21, 2024.</li>
<li>Scan or Type your answers and submit only one file. (If you submit several files only the recent one uploaded will be graded).</li>
<li>Preferably save your file as PDF before uploading. Submit in Canvas under Homework 4.</li>
<li>These questions are from <em>An Introduction to Statistical Learning with Applications in R</em> by James, et. al., chapter 5.</li>
</ol>
</section>
<section id="problem-1" class="level2">
<h2 class="anchored" data-anchor-id="problem-1">Problem 1</h2>
<p>We will review <span class="math inline">\(k\)</span>-fold cross-validation.</p>
<ol type="a">
<li>Explain how <span class="math inline">\(k\)</span>-fold cross-validation is implemented.<br>
<strong>Answer</strong><br>
𝑘-fold cross-validation is implemented by randomly dividing data into 𝐾 <strong>subsets</strong> (folds) of approximately equal size, <span class="math inline">\(n_k\)</span>. We treat the first fold as a validation set, and we have the method fit on the remaining 𝑘 − 1 folds. The Mean Squared Error (<span class="math inline">\(MSE_1\)</span>) is then computed on the observations in the held-out fold. We repeat this procedure 𝑘 times, where each time, a different group of observations is treated as a validation set. This results in k estimates of the test error:<br>
<span class="math inline">\(MSE_1\)</span>, <span class="math inline">\(MSE_2\)</span>,…, <span class="math inline">\(MSE_k\)</span></li>
</ol>
<p><span class="math inline">\(CV(k)\)</span> = <span class="math inline">\(\frac{1}{K}\)</span> <span class="math inline">\(\Sigma_{j=1}^{K} MSE_j\)</span><br>
(b) What are the advantages and disadvantages of <span class="math inline">\(k\)</span>-fold cross-validation relative to:</p>
<pre><code> i. The validation set approach?
 ii. LOOVC?  </code></pre>
<p><strong>Answer</strong><br>
<em>Advantages</em>:</p>
<pre><code>-Is less computationally intensive for models  
-Is fit only 𝐾 « 𝑛 times  
-Does not lose in estimation quality  
-Variability in error estimates is negligible  
-Does not lose in estimate efficiency  
-Gives more accurate estimates of the test error rate  </code></pre>
<p><em>Disadvantages</em>:</p>
<pre><code>-Estimates model’s test error with more bias  </code></pre>
<div style="page-break-after: always;"></div>
</section>
<section id="problem-2" class="level2">
<h2 class="anchored" data-anchor-id="problem-2">Problem 2</h2>
<p>We will now derive the probability that a given observation is part of a bootstrap sample. Suppose that we obtain a bootstrap sample from a set of <span class="math inline">\(n\)</span> observations.</p>
<ol type="a">
<li><p>What is the probability that the first bootstrap observation is not the <span class="math inline">\(j\)</span>th observation from the original sample? Justify your answer.<br>
<strong>Answer</strong><br>
The probability that the first bootstrap observation is not the <span class="math inline">\(jth\)</span> observation from the original sample is <span class="math inline">\(1 - \frac{1}{n}\)</span> This is because there are <span class="math inline">\(n\)</span> samples, and we are equally likely to pick each observation when taking our first bootstrap observation.</p></li>
<li><p>What is the probability that the second bootstrap observation is not the <span class="math inline">\(j\)</span>th observation from the original sample?<br>
<strong>Answer</strong><br>
Since bootstrap observations are sampled from the original observations with replacement, the probability that the second bootstrap observation is not the <span class="math inline">\(jth\)</span> observation from the original sample is again <span class="math inline">\(1 - \frac{1}{n}\)</span>.</p></li>
<li><p>Argue that the probability that the <span class="math inline">\(j\)</span>th observation is not in the bootstrap sample is <span class="math inline">\(\left(1 − \frac{1}{n}\right)^n\)</span>.<br>
<strong>Answer</strong><br>
As the probability that any particular bootstrap observation is not the <span class="math inline">\(jth\)</span> observation from the original sample is <span class="math inline">\(1 - \frac{1}{n}\)</span>, and we are taking a total of <span class="math inline">\(n\)</span> bootstrap observations from the original set of <span class="math inline">\(n\)</span> observations, the probability that the <span class="math inline">\(jth\)</span> observation is not in the bootstrap sample is<br>
<span class="math inline">\(\left(1 − \frac{1}{n}\right)^n\)</span>. Note that we are multiplying probabilities because sampling with replacement means that the individual bootstrap observations in the bootstrap sample are independent.</p></li>
<li><p>When <span class="math inline">\(n = 5\)</span>, what is the probability that the <span class="math inline">\(j\)</span>th observation is in the bootstrap sample?<br>
<strong>Answer</strong><br>
For <span class="math inline">\(n = 5\)</span>, <span class="math inline">\(1 -\left(1 − \frac{1}{5}\right)^5 = 0.67232\)</span></p></li>
<li><p>When <span class="math inline">\(n = 100\)</span>, what is the probability that the <span class="math inline">\(j\)</span>th observation is in the bootstrap sample?<br>
<strong>Answer</strong><br>
For <span class="math inline">\(n = 100\)</span>, <span class="math inline">\(1 -\left(1 − \frac{1}{100}\right)^{100} = 0.633968\)</span></p></li>
<li><p>When <span class="math inline">\(n = 10,000\)</span>, what is the probability that the jth observation is in the bootstrap sample?<br>
<strong>Answer</strong><br>
For <span class="math inline">\(n = 10,000\)</span>, <span class="math inline">\(1 -\left(1 − \frac{1}{10,000}\right)^{10,000} = 0.632139\)</span></p></li>
<li><p>Create a plot that displays, for each integer value of <span class="math inline">\(n\)</span> from 1 to 100,000, the probability that the <span class="math inline">\(j\)</span>th observation is in the bootstrap sample. Comment on what you observe.</p></li>
</ol>
<div class="cell">
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a>x <span class="ot">=</span><span class="fu">seq</span>(<span class="dv">1</span><span class="sc">:</span><span class="dv">100000</span>)</span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a>p.x <span class="ot">=</span> <span class="dv">1</span> <span class="sc">-</span> (<span class="dv">1</span> <span class="sc">-</span> <span class="dv">1</span><span class="sc">/</span>x)<span class="sc">^</span>x</span>
<span id="cb4-3"><a href="#cb4-3" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(x,p.x,<span class="at">xlab =</span> <span class="st">"n"</span>, <span class="at">ylab =</span> <span class="st">"Probability"</span>, <span class="at">type =</span> <span class="st">"l"</span>, <span class="at">xlim =</span> <span class="fu">c</span>(<span class="dv">0</span>,<span class="dv">500</span>))</span>
<span id="cb4-4"><a href="#cb4-4" aria-hidden="true" tabindex="-1"></a><span class="fu">lines</span>(x, <span class="at">y=</span><span class="fu">rep</span>(<span class="dv">1-1</span><span class="sc">/</span><span class="fu">exp</span>(<span class="dv">1</span>), <span class="fu">length</span>(x)), <span class="at">type =</span> <span class="st">"l"</span>, <span class="at">col =</span> <span class="st">"blue"</span>)</span>
<span id="cb4-5"><a href="#cb4-5" aria-hidden="true" tabindex="-1"></a><span class="fu">legend</span>(<span class="st">"topright"</span>, <span class="at">legend =</span> <span class="st">"1-1/exp(1)"</span>, <span class="at">col =</span> <span class="st">"blue"</span>, <span class="at">lty =</span><span class="dv">1</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="homework4_4322s_files/figure-html/unnamed-chunk-1-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>By L’Hopital’s rule <span class="math inline">\(\lim_{n\to\inf} (1-\frac{1}{n})^n = \frac{1}{exp(1)}\)</span></p>
<ol start="8" type="a">
<li>We will now investigate numerically the probability that a bootstrap sample of size <span class="math inline">\(n = 100\)</span> contains the <span class="math inline">\(j\)</span>th observation. Here <span class="math inline">\(j = 4\)</span>. We repeatedly create bootstrap samples, and each time we record whether or not the fourth observation is contained in the bootstrap sample.</li>
</ol>
<div class="cell">
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a>store <span class="ot">&lt;-</span> <span class="fu">rep</span>(<span class="cn">NA</span>, <span class="dv">10000</span>)</span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a> <span class="cf">for</span>(i <span class="cf">in</span> <span class="dv">1</span><span class="sc">:</span><span class="dv">10000</span>){</span>
<span id="cb5-3"><a href="#cb5-3" aria-hidden="true" tabindex="-1"></a>store[i] <span class="ot">&lt;-</span> <span class="fu">sum</span>(<span class="fu">sample</span> (<span class="dv">1</span><span class="sc">:</span><span class="dv">100</span> , <span class="at">rep=</span><span class="cn">TRUE</span>) <span class="sc">==</span> <span class="dv">4</span>) <span class="sc">&gt;</span> <span class="dv">0</span></span>
<span id="cb5-4"><a href="#cb5-4" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb5-5"><a href="#cb5-5" aria-hidden="true" tabindex="-1"></a><span class="fu">mean</span>(store)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.6344</code></pre>
</div>
</div>
<p>Comment on the results obtained.<br>
The mean(store) call yields the proportion of bootstrap samples that contain the 4th observation. As expected, we see the selection probability is approximately equal to <span class="math inline">\(1 - (1 - 1/100)^{100}\)</span>, which is approximately equal to <span class="math inline">\(1 - exp(-1)\)</span>.</p>
<div style="page-break-after: always;"></div>
</section>
<section id="problem-3" class="level2">
<h2 class="anchored" data-anchor-id="problem-3">Problem 3</h2>
<p>We will perform cross-validation on a simulated data set.</p>
<ol type="a">
<li>Generate a simulated data set as follows:</li>
</ol>
<div class="cell">
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">1</span>)</span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a>x<span class="ot">=</span><span class="fu">rnorm</span>(<span class="dv">100</span>)</span>
<span id="cb7-3"><a href="#cb7-3" aria-hidden="true" tabindex="-1"></a>y<span class="ot">=</span>x<span class="dv">-2</span><span class="sc">*</span>x<span class="sc">^</span><span class="dv">2</span><span class="sc">+</span> <span class="fu">rnorm</span>(<span class="dv">100</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>In this data set, what is n and what is p? Write out the model used to generate the data in equation form.<br>
<strong>Answer</strong><br>
Model: <span class="math inline">\(Y = X - 2X^2 + \epsilon\)</span><br>
n = 100 observations<br>
p = 1 predictor</p>
<ol start="2" type="a">
<li>Create a scatterplot of X against Y . Comment on what you find.</li>
</ol>
<div class="cell">
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(x,y)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="homework4_4322s_files/figure-html/unnamed-chunk-4-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>The shape of the plot is parabolic, not linear.</p>
<ol start="3" type="a">
<li>Set a random seed, and then compute the LOOCV errors that result from fitting the following four models using least squares:
<ol type="i">
<li><span class="math inline">\(Y = \beta_0 + \beta_1 X + \epsilon\)</span></li>
<li><span class="math inline">\(Y = \beta_0 + \beta_1 X + \beta_2X^2 + \epsilon\)</span></li>
<li><span class="math inline">\(Y = \beta_0 + \beta_1 X + \beta_2X^2 + \beta_3X^3 + \epsilon\)</span></li>
<li><span class="math inline">\(Y = \beta_0 + \beta_1 X + \beta_2X^2 + \beta_3X^3 + \beta_4X^4 + \epsilon\)</span></li>
</ol></li>
</ol>
<p><span class="math inline">\(Note\)</span>: you might find it helpful to use the <code>data.frame()</code> function to create a single data set containing both <span class="math inline">\(X\)</span> and <span class="math inline">\(Y\)</span>.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(boot)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: package 'boot' was built under R version 4.2.3</code></pre>
</div>
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">106</span>)</span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a>xy <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(x,y)</span>
<span id="cb11-3"><a href="#cb11-3" aria-hidden="true" tabindex="-1"></a><span class="co">#create list to store the MSEs</span></span>
<span id="cb11-4"><a href="#cb11-4" aria-hidden="true" tabindex="-1"></a>cv.error <span class="ot">&lt;-</span> <span class="fu">rep</span>(<span class="dv">0</span>,<span class="dv">4</span>)</span>
<span id="cb11-5"><a href="#cb11-5" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> (i <span class="cf">in</span> <span class="dv">1</span><span class="sc">:</span><span class="dv">4</span>) {</span>
<span id="cb11-6"><a href="#cb11-6" aria-hidden="true" tabindex="-1"></a>  glm.fit <span class="ot">&lt;-</span> <span class="fu">glm</span>(y <span class="sc">~</span> <span class="fu">poly</span>(x,i), <span class="at">data =</span> xy)</span>
<span id="cb11-7"><a href="#cb11-7" aria-hidden="true" tabindex="-1"></a>  cv.error[i] <span class="ot">=</span> <span class="fu">cv.glm</span>(xy,glm.fit)<span class="sc">$</span>delta[<span class="dv">1</span>]</span>
<span id="cb11-8"><a href="#cb11-8" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb11-9"><a href="#cb11-9" aria-hidden="true" tabindex="-1"></a>cv.error</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 7.2881616 0.9374236 0.9566218 0.9539049</code></pre>
</div>
</div>
<ol start="4" type="a">
<li>Repeat (c) using another random seed, and report your results. Are your results the same as what you got in (c)? Why?</li>
</ol>
<div class="cell">
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">21</span>)</span>
<span id="cb13-2"><a href="#cb13-2" aria-hidden="true" tabindex="-1"></a>xy <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(x,y)</span>
<span id="cb13-3"><a href="#cb13-3" aria-hidden="true" tabindex="-1"></a><span class="co">#create list to store the MSEs</span></span>
<span id="cb13-4"><a href="#cb13-4" aria-hidden="true" tabindex="-1"></a>cv.error <span class="ot">&lt;-</span> <span class="fu">rep</span>(<span class="dv">0</span>,<span class="dv">4</span>)</span>
<span id="cb13-5"><a href="#cb13-5" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> (i <span class="cf">in</span> <span class="dv">1</span><span class="sc">:</span><span class="dv">4</span>) {</span>
<span id="cb13-6"><a href="#cb13-6" aria-hidden="true" tabindex="-1"></a>  glm.fit <span class="ot">&lt;-</span> <span class="fu">glm</span>(y <span class="sc">~</span> <span class="fu">poly</span>(x,i), <span class="at">data =</span> xy)</span>
<span id="cb13-7"><a href="#cb13-7" aria-hidden="true" tabindex="-1"></a>  cv.error[i] <span class="ot">=</span> <span class="fu">cv.glm</span>(xy,glm.fit)<span class="sc">$</span>delta[<span class="dv">1</span>]</span>
<span id="cb13-8"><a href="#cb13-8" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb13-9"><a href="#cb13-9" aria-hidden="true" tabindex="-1"></a>cv.error</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 7.2881616 0.9374236 0.9566218 0.9539049</code></pre>
</div>
</div>
<p>The answers I obtained were the same as what I got in (c) because LOOCV always yields the same results.</p>
<ol start="5" type="a">
<li>Which of the models in (c) had the smallest LOOCV error? Is this what you expected? Explain your answer.<br>
<strong>Answer</strong><br>
Our model with the smallest LOOCV error is the quadratic polynomial model, as we made <span class="math inline">\(y\)</span> the result of <span class="math inline">\(x^2\)</span>.<br>
</li>
<li>Comment on the statistical significance of the coefficient estimates that results from fitting each of the models in (c) using least squares. Do these results agree with the conclusions drawn based on the cross-validation results?</li>
</ol>
<div class="cell">
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a>glm.fit <span class="ot">&lt;-</span> <span class="fu">glm</span>(y <span class="sc">~</span> <span class="fu">poly</span>(x,<span class="dv">4</span>), <span class="at">data =</span> xy)</span>
<span id="cb15-2"><a href="#cb15-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(glm.fit)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
glm(formula = y ~ poly(x, 4), data = xy)

Deviance Residuals: 
    Min       1Q   Median       3Q      Max  
-2.0550  -0.6212  -0.1567   0.5952   2.2267  

Coefficients:
             Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)  -1.55002    0.09591 -16.162  &lt; 2e-16 ***
poly(x, 4)1   6.18883    0.95905   6.453 4.59e-09 ***
poly(x, 4)2 -23.94830    0.95905 -24.971  &lt; 2e-16 ***
poly(x, 4)3   0.26411    0.95905   0.275    0.784    
poly(x, 4)4   1.25710    0.95905   1.311    0.193    
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

(Dispersion parameter for gaussian family taken to be 0.9197797)

    Null deviance: 700.852  on 99  degrees of freedom
Residual deviance:  87.379  on 95  degrees of freedom
AIC: 282.3

Number of Fisher Scoring iterations: 2</code></pre>
</div>
</div>
<p>We see that <span class="math inline">\(x\)</span> and <span class="math inline">\(x^2\)</span> are both statistically significant, which is what we expected from the conclusions drawn from the cross-validation results in part (c). </p>
</section>
<section id="problem-4" class="level2">
<h2 class="anchored" data-anchor-id="problem-4">Problem 4</h2>
<p>We will use a logistic regression to predict the probability of <code>default</code> using income and <code>balance</code> on the <code>Default</code> data set in the ISLR package. We will now estimate the test error of this logistic regression model using the validation set approach. Do not forget to set a random seed before beginning your analysis.</p>
<ol type="a">
<li>Fit a logistic regression model that uses income and balance to predict default.<br>
<strong>Answer</strong></li>
</ol>
<div class="cell">
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ISLR)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: package 'ISLR' was built under R version 4.2.3</code></pre>
</div>
<div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a><span class="fu">attach</span>(Default)</span>
<span id="cb19-2"><a href="#cb19-2" aria-hidden="true" tabindex="-1"></a>defaultLog <span class="ot">&lt;-</span> <span class="fu">glm</span>(default <span class="sc">~</span> income <span class="sc">+</span> balance, <span class="at">family =</span> <span class="st">"binomial"</span>)</span>
<span id="cb19-3"><a href="#cb19-3" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(defaultLog)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
glm(formula = default ~ income + balance, family = "binomial")

Deviance Residuals: 
    Min       1Q   Median       3Q      Max  
-2.4725  -0.1444  -0.0574  -0.0211   3.7245  

Coefficients:
              Estimate Std. Error z value Pr(&gt;|z|)    
(Intercept) -1.154e+01  4.348e-01 -26.545  &lt; 2e-16 ***
income       2.081e-05  4.985e-06   4.174 2.99e-05 ***
balance      5.647e-03  2.274e-04  24.836  &lt; 2e-16 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

(Dispersion parameter for binomial family taken to be 1)

    Null deviance: 2920.6  on 9999  degrees of freedom
Residual deviance: 1579.0  on 9997  degrees of freedom
AIC: 1585

Number of Fisher Scoring iterations: 8</code></pre>
</div>
</div>
<ol start="2" type="a">
<li>Using the validation set approach, estimate the test error of this model. In order to do this, you must perform the following steps:
<ol type="i">
<li>Split the sample set into a training set and a validation set.<br>
</li>
<li>Fit a multiple logistic regression model using only the training observations.<br>
</li>
<li>Obtain a prediction of default status for each individual in the validation set by computing the posterior probability of default for that individual, and classifying the individual to the default category if the posterior probability is greater than 0.5.<br>
</li>
<li>Compute the validation set error, which is the fraction of the observations in the validation set that are misclassified.<br>
<strong>Answer</strong></li>
</ol></li>
</ol>
<div class="cell">
<div class="sourceCode cell-code" id="cb21"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">21</span>)</span>
<span id="cb21-2"><a href="#cb21-2" aria-hidden="true" tabindex="-1"></a>sample <span class="ot">&lt;-</span> <span class="fu">sample</span>(<span class="dv">1</span><span class="sc">:</span><span class="fu">nrow</span>(Default),<span class="fu">nrow</span>(Default)<span class="sc">/</span><span class="dv">2</span>)</span>
<span id="cb21-3"><a href="#cb21-3" aria-hidden="true" tabindex="-1"></a>train <span class="ot">&lt;-</span> Default[sample,]</span>
<span id="cb21-4"><a href="#cb21-4" aria-hidden="true" tabindex="-1"></a>test <span class="ot">&lt;-</span> Default[<span class="sc">-</span>sample,]</span>
<span id="cb21-5"><a href="#cb21-5" aria-hidden="true" tabindex="-1"></a>defaultLog2 <span class="ot">&lt;-</span> <span class="fu">glm</span>(default <span class="sc">~</span> income <span class="sc">+</span> balance, <span class="at">data =</span> train, <span class="at">family =</span> <span class="st">"binomial"</span>)</span>
<span id="cb21-6"><a href="#cb21-6" aria-hidden="true" tabindex="-1"></a>glm.pred <span class="ot">&lt;-</span> <span class="fu">predict.glm</span>(defaultLog2, <span class="at">newdata =</span> test, <span class="at">type =</span> <span class="st">"response"</span>)</span>
<span id="cb21-7"><a href="#cb21-7" aria-hidden="true" tabindex="-1"></a>predicted <span class="ot">&lt;-</span> <span class="fu">ifelse</span>(glm.pred <span class="sc">&lt;</span> <span class="fl">0.5</span>, <span class="st">"No"</span>, <span class="st">"Yes"</span>)</span>
<span id="cb21-8"><a href="#cb21-8" aria-hidden="true" tabindex="-1"></a>(<span class="at">confmat =</span> <span class="fu">table</span>(predicted, test<span class="sc">$</span>default))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>         
predicted   No  Yes
      No  4807  122
      Yes   22   49</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb23"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a>(confmat[<span class="dv">1</span>,<span class="dv">2</span>]<span class="sc">+</span>confmat[<span class="dv">2</span>,<span class="dv">1</span>])<span class="sc">/</span><span class="dv">5000</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.0288</code></pre>
</div>
</div>
<p>Validation set error rate: 2.88%</p>
<ol start="3" type="a">
<li>Repeat the process in (b) three times, using three different splits of the observations into a training set and a validation set. Comment on the results obtained.</li>
</ol>
<div class="cell">
<div class="sourceCode cell-code" id="cb25"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">22</span>)</span>
<span id="cb25-2"><a href="#cb25-2" aria-hidden="true" tabindex="-1"></a>sample <span class="ot">&lt;-</span> <span class="fu">sample</span>(<span class="dv">1</span><span class="sc">:</span><span class="fu">nrow</span>(Default),<span class="fu">nrow</span>(Default)<span class="sc">/</span><span class="dv">2</span>)</span>
<span id="cb25-3"><a href="#cb25-3" aria-hidden="true" tabindex="-1"></a>train <span class="ot">&lt;-</span> Default[sample,]</span>
<span id="cb25-4"><a href="#cb25-4" aria-hidden="true" tabindex="-1"></a>test <span class="ot">&lt;-</span> Default[<span class="sc">-</span>sample,]</span>
<span id="cb25-5"><a href="#cb25-5" aria-hidden="true" tabindex="-1"></a>defaultLog2 <span class="ot">&lt;-</span> <span class="fu">glm</span>(default <span class="sc">~</span> income <span class="sc">+</span> balance, <span class="at">data =</span> train, <span class="at">family =</span> <span class="st">"binomial"</span>)</span>
<span id="cb25-6"><a href="#cb25-6" aria-hidden="true" tabindex="-1"></a>glm.pred <span class="ot">&lt;-</span> <span class="fu">predict.glm</span>(defaultLog2, <span class="at">newdata =</span> test, <span class="at">type =</span> <span class="st">"response"</span>)</span>
<span id="cb25-7"><a href="#cb25-7" aria-hidden="true" tabindex="-1"></a>predicted <span class="ot">&lt;-</span> <span class="fu">ifelse</span>(glm.pred <span class="sc">&lt;</span> <span class="fl">0.5</span>, <span class="st">"No"</span>, <span class="st">"Yes"</span>)</span>
<span id="cb25-8"><a href="#cb25-8" aria-hidden="true" tabindex="-1"></a>(<span class="at">confmat =</span> <span class="fu">table</span>(predicted, test<span class="sc">$</span>default))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>         
predicted   No  Yes
      No  4813  119
      Yes   18   50</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb27"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a>(confmat[<span class="dv">1</span>,<span class="dv">2</span>]<span class="sc">+</span>confmat[<span class="dv">2</span>,<span class="dv">1</span>])<span class="sc">/</span><span class="dv">5000</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.0274</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb29"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb29-1"><a href="#cb29-1" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">23</span>)</span>
<span id="cb29-2"><a href="#cb29-2" aria-hidden="true" tabindex="-1"></a>sample <span class="ot">&lt;-</span> <span class="fu">sample</span>(<span class="dv">1</span><span class="sc">:</span><span class="fu">nrow</span>(Default),<span class="fu">nrow</span>(Default)<span class="sc">/</span><span class="dv">2</span>)</span>
<span id="cb29-3"><a href="#cb29-3" aria-hidden="true" tabindex="-1"></a>train <span class="ot">&lt;-</span> Default[sample,]</span>
<span id="cb29-4"><a href="#cb29-4" aria-hidden="true" tabindex="-1"></a>test <span class="ot">&lt;-</span> Default[<span class="sc">-</span>sample,]</span>
<span id="cb29-5"><a href="#cb29-5" aria-hidden="true" tabindex="-1"></a>defaultLog2 <span class="ot">&lt;-</span> <span class="fu">glm</span>(default <span class="sc">~</span> income <span class="sc">+</span> balance, <span class="at">data =</span> train, <span class="at">family =</span> <span class="st">"binomial"</span>)</span>
<span id="cb29-6"><a href="#cb29-6" aria-hidden="true" tabindex="-1"></a>glm.pred <span class="ot">&lt;-</span> <span class="fu">predict.glm</span>(defaultLog2, <span class="at">newdata =</span> test, <span class="at">type =</span> <span class="st">"response"</span>)</span>
<span id="cb29-7"><a href="#cb29-7" aria-hidden="true" tabindex="-1"></a>predicted <span class="ot">&lt;-</span> <span class="fu">ifelse</span>(glm.pred <span class="sc">&lt;</span> <span class="fl">0.5</span>, <span class="st">"No"</span>, <span class="st">"Yes"</span>)</span>
<span id="cb29-8"><a href="#cb29-8" aria-hidden="true" tabindex="-1"></a>(<span class="at">confmat =</span> <span class="fu">table</span>(predicted, test<span class="sc">$</span>default))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>         
predicted   No  Yes
      No  4811  135
      Yes   10   44</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb31"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb31-1"><a href="#cb31-1" aria-hidden="true" tabindex="-1"></a>(confmat[<span class="dv">1</span>,<span class="dv">2</span>]<span class="sc">+</span>confmat[<span class="dv">2</span>,<span class="dv">1</span>])<span class="sc">/</span><span class="dv">5000</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.029</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb33"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb33-1"><a href="#cb33-1" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">24</span>)</span>
<span id="cb33-2"><a href="#cb33-2" aria-hidden="true" tabindex="-1"></a>sample <span class="ot">&lt;-</span> <span class="fu">sample</span>(<span class="dv">1</span><span class="sc">:</span><span class="fu">nrow</span>(Default),<span class="fu">nrow</span>(Default)<span class="sc">/</span><span class="dv">2</span>)</span>
<span id="cb33-3"><a href="#cb33-3" aria-hidden="true" tabindex="-1"></a>train <span class="ot">&lt;-</span> Default[sample,]</span>
<span id="cb33-4"><a href="#cb33-4" aria-hidden="true" tabindex="-1"></a>test <span class="ot">&lt;-</span> Default[<span class="sc">-</span>sample,]</span>
<span id="cb33-5"><a href="#cb33-5" aria-hidden="true" tabindex="-1"></a>defaultLog2 <span class="ot">&lt;-</span> <span class="fu">glm</span>(default <span class="sc">~</span> income <span class="sc">+</span> balance, <span class="at">data =</span> train, <span class="at">family =</span> <span class="st">"binomial"</span>)</span>
<span id="cb33-6"><a href="#cb33-6" aria-hidden="true" tabindex="-1"></a>glm.pred <span class="ot">&lt;-</span> <span class="fu">predict.glm</span>(defaultLog2, <span class="at">newdata =</span> test, <span class="at">type =</span> <span class="st">"response"</span>)</span>
<span id="cb33-7"><a href="#cb33-7" aria-hidden="true" tabindex="-1"></a>predicted <span class="ot">&lt;-</span> <span class="fu">ifelse</span>(glm.pred <span class="sc">&lt;</span> <span class="fl">0.5</span>, <span class="st">"No"</span>, <span class="st">"Yes"</span>)</span>
<span id="cb33-8"><a href="#cb33-8" aria-hidden="true" tabindex="-1"></a>(<span class="at">confmat =</span> <span class="fu">table</span>(predicted, test<span class="sc">$</span>default))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>         
predicted   No  Yes
      No  4823  101
      Yes   22   54</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb35"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb35-1"><a href="#cb35-1" aria-hidden="true" tabindex="-1"></a>(confmat[<span class="dv">1</span>,<span class="dv">2</span>]<span class="sc">+</span>confmat[<span class="dv">2</span>,<span class="dv">1</span>])<span class="sc">/</span><span class="dv">5000</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.0246</code></pre>
</div>
</div>
<p>All three splits’ error rates stayed in the 2.4% to 3.0% range.</p>
<div style="page-break-after: always;"></div>
</section>
<section id="problem-5" class="level2">
<h2 class="anchored" data-anchor-id="problem-5">Problem 5</h2>
<p>We will now consider the <code>Boston</code> housing data set, from the <code>ISLR2</code> library.</p>
<ol type="a">
<li>Based on this data set, provide an estimate for the population mean of <code>medv</code>. Call this estimate <span class="math inline">\(\hat{\mu}\)</span>.</li>
</ol>
<div class="cell">
<div class="sourceCode cell-code" id="cb37"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb37-1"><a href="#cb37-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ISLR2)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: package 'ISLR2' was built under R version 4.2.3</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>
Attaching package: 'ISLR2'</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>The following objects are masked from 'package:ISLR':

    Auto, Credit</code></pre>
</div>
<div class="sourceCode cell-code" id="cb41"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb41-1"><a href="#cb41-1" aria-hidden="true" tabindex="-1"></a>mu.hat <span class="ot">=</span> <span class="fu">mean</span>(Boston<span class="sc">$</span>medv)</span>
<span id="cb41-2"><a href="#cb41-2" aria-hidden="true" tabindex="-1"></a>mu.hat</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 22.53281</code></pre>
</div>
</div>
<ol start="2" type="a">
<li>Provide an estimate of the standard error of <span class="math inline">\(\hat{\mu}\)</span>. Interpret this result.<br>
<em>Hint: We can compute the standard error of the sample mean by dividing the sample standard deviation by the square root of the number of observations.</em></li>
</ol>
<div class="cell">
<div class="sourceCode cell-code" id="cb43"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb43-1"><a href="#cb43-1" aria-hidden="true" tabindex="-1"></a>se.muhat <span class="ot">=</span> <span class="fu">sd</span>(Boston<span class="sc">$</span>medv)<span class="sc">/</span><span class="fu">sqrt</span>(<span class="fu">nrow</span>(Boston))</span>
<span id="cb43-2"><a href="#cb43-2" aria-hidden="true" tabindex="-1"></a>se.muhat</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.4088611</code></pre>
</div>
</div>
<ol start="3" type="a">
<li>Now estimate the standard error of <span class="math inline">\(\hat{\mu}\)</span> using the bootstrap. How does this compare to your answer from (b)?</li>
</ol>
<div class="cell">
<div class="sourceCode cell-code" id="cb45"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb45-1"><a href="#cb45-1" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">1</span>)</span>
<span id="cb45-2"><a href="#cb45-2" aria-hidden="true" tabindex="-1"></a>boot.fn <span class="ot">=</span> <span class="cf">function</span>(data,index){</span>
<span id="cb45-3"><a href="#cb45-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">return</span>(<span class="fu">mean</span>(data[index]))</span>
<span id="cb45-4"><a href="#cb45-4" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb45-5"><a href="#cb45-5" aria-hidden="true" tabindex="-1"></a>bootstrap <span class="ot">=</span> <span class="fu">boot</span>(Boston<span class="sc">$</span>medv, boot.fn, <span class="dv">1000</span>)</span>
<span id="cb45-6"><a href="#cb45-6" aria-hidden="true" tabindex="-1"></a>bootstrap</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
ORDINARY NONPARAMETRIC BOOTSTRAP


Call:
boot(data = Boston$medv, statistic = boot.fn, R = 1000)


Bootstrap Statistics :
    original      bias    std. error
t1* 22.53281 0.007650791   0.4106622</code></pre>
</div>
</div>
<p>Our standard error is 0.4106622, therefore it strongly agrees with the calculated standard error from part b.</p>
<ol start="4" type="a">
<li>Based on your bootstrap estimate from (c), provide a 95% confidence interval for the mean of <code>medv</code>. Compare it to the results obtained using t.test(Boston$medv).<br>
<em>Hint: You can approximate a 95% confidence interval using the formula <span class="math inline">\(\left[\hat{\mu} − 2SE(\hat{\mu}), \hat{\mu} + 2SE(\hat{\mu})\right]\)</span>.</em></li>
</ol>
<div class="cell">
<div class="sourceCode cell-code" id="cb47"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb47-1"><a href="#cb47-1" aria-hidden="true" tabindex="-1"></a>mu.hat <span class="sc">+</span> <span class="fu">c</span>(<span class="sc">-</span><span class="dv">1</span>,<span class="dv">1</span>)<span class="sc">*</span><span class="dv">2</span><span class="sc">*</span><span class="fu">sd</span>(bootstrap<span class="sc">$</span>t)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 21.71148 23.35413</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb49"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb49-1"><a href="#cb49-1" aria-hidden="true" tabindex="-1"></a><span class="fu">t.test</span>(Boston<span class="sc">$</span>medv)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    One Sample t-test

data:  Boston$medv
t = 55.111, df = 505, p-value &lt; 2.2e-16
alternative hypothesis: true mean is not equal to 0
95 percent confidence interval:
 21.72953 23.33608
sample estimates:
mean of x 
 22.53281 </code></pre>
</div>
</div>
<p>The confidence interval from the bootstrap estimate is [21.71148, 23.35413] and the confidence interval from the t-test is [21.72953, 23.33608]. The obtained results are very similar.</p>
<ol start="5" type="a">
<li>Based on this data set, provide an estimate, <span class="math inline">\(\hat{\mu}_{med}\)</span>, for the median value of <code>medv</code> in the population.</li>
</ol>
<div class="cell">
<div class="sourceCode cell-code" id="cb51"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb51-1"><a href="#cb51-1" aria-hidden="true" tabindex="-1"></a>med.hat <span class="ot">=</span> <span class="fu">median</span>(Boston<span class="sc">$</span>medv)</span>
<span id="cb51-2"><a href="#cb51-2" aria-hidden="true" tabindex="-1"></a>med.hat</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 21.2</code></pre>
</div>
</div>
<ol start="6" type="a">
<li>We now would like to estimate the standard error of <span class="math inline">\(\hat{\mu}_{med}\)</span>. Unfortunately, there is no simple formula for computing the standard error of the median. Instead, estimate the standard error of the median using the bootstrap. Comment on your findings.</li>
</ol>
<div class="cell">
<div class="sourceCode cell-code" id="cb53"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb53-1"><a href="#cb53-1" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">1</span>)</span>
<span id="cb53-2"><a href="#cb53-2" aria-hidden="true" tabindex="-1"></a>boot.fn <span class="ot">&lt;-</span> <span class="cf">function</span>(data, index) {</span>
<span id="cb53-3"><a href="#cb53-3" aria-hidden="true" tabindex="-1"></a>  medval <span class="ot">&lt;-</span> <span class="fu">median</span>(data[index])</span>
<span id="cb53-4"><a href="#cb53-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">return</span> (medval)</span>
<span id="cb53-5"><a href="#cb53-5" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb53-6"><a href="#cb53-6" aria-hidden="true" tabindex="-1"></a>se_medval <span class="ot">=</span> <span class="fu">boot</span>(Boston<span class="sc">$</span>medv, boot.fn, <span class="at">R =</span> <span class="dv">1000</span>)</span>
<span id="cb53-7"><a href="#cb53-7" aria-hidden="true" tabindex="-1"></a>se_medval</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
ORDINARY NONPARAMETRIC BOOTSTRAP


Call:
boot(data = Boston$medv, statistic = boot.fn, R = 1000)


Bootstrap Statistics :
    original  bias    std. error
t1*     21.2 0.02295   0.3778075</code></pre>
</div>
</div>
<p>The standard error is 0.3778075, it is relatively small.</p>
<ol start="7" type="a">
<li>Based on this data set, provide an estimate for the tenth percentile of <code>medv</code> in Boston census tracts. Call this quantity <span class="math inline">\(\hat{\mu}_{0.1}\)</span>. (You can use the <code>quantile()</code> function.)</li>
</ol>
<div class="cell">
<div class="sourceCode cell-code" id="cb55"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb55-1"><a href="#cb55-1" aria-hidden="true" tabindex="-1"></a>(<span class="at">mean.quantile =</span> <span class="fu">quantile</span>(Boston<span class="sc">$</span>medv,<span class="fl">0.1</span>,<span class="at">type =</span> <span class="dv">5</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  10% 
12.71 </code></pre>
</div>
</div>
<ol start="8" type="a">
<li>Use the bootstrap to estimate the standard error of <span class="math inline">\(\hat{\mu}_{0.1}\)</span>. Comment on your findings.</li>
</ol>
<div class="cell">
<div class="sourceCode cell-code" id="cb57"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb57-1"><a href="#cb57-1" aria-hidden="true" tabindex="-1"></a>quantile.fn <span class="ot">=</span> <span class="cf">function</span>(data,index) <span class="fu">quantile</span>(data[index],<span class="fl">0.1</span>,<span class="at">type =</span> <span class="dv">5</span>)</span>
<span id="cb57-2"><a href="#cb57-2" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">100</span>)</span>
<span id="cb57-3"><a href="#cb57-3" aria-hidden="true" tabindex="-1"></a>(<span class="at">boot.out =</span> <span class="fu">boot</span>(Boston<span class="sc">$</span>medv,quantile.fn,<span class="dv">10000</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
ORDINARY NONPARAMETRIC BOOTSTRAP


Call:
boot(data = Boston$medv, statistic = quantile.fn, R = 10000)


Bootstrap Statistics :
    original   bias    std. error
t1*    12.71 0.018014   0.5089463</code></pre>
</div>
</div>
<p>The estimate may be off by about 0.51</p>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->



</body></html>