<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.3.450">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>MATH 4322 - Homework 2</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="homework_2_sp24_s_files/libs/clipboard/clipboard.min.js"></script>
<script src="homework_2_sp24_s_files/libs/quarto-html/quarto.js"></script>
<script src="homework_2_sp24_s_files/libs/quarto-html/popper.min.js"></script>
<script src="homework_2_sp24_s_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="homework_2_sp24_s_files/libs/quarto-html/anchor.min.js"></script>
<link href="homework_2_sp24_s_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="homework_2_sp24_s_files/libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="homework_2_sp24_s_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="homework_2_sp24_s_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="homework_2_sp24_s_files/libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">

  <script src="https://polyfill.io/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

</head>

<body class="fullcontent">

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">

<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">MATH 4322 - Homework 2</h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  

</header>

<section id="instructions" class="level2">
<h2 class="anchored" data-anchor-id="instructions">Instructions</h2>
<ul>
<li>Due February 15, 2024 at 11:59 pm</li>
<li>Answer all questions fully</li>
<li>Submit the answers in one file, preferably PDF, then upload in Canvas.</li>
<li>These questions are from <strong>Introduction to Statistical Learning, 2nd edition</strong>, chapters 3 and 6.</li>
</ul>
</section>
<section id="problem-1" class="level2">
<h2 class="anchored" data-anchor-id="problem-1">Problem 1</h2>
<p>The following output is based on predicting <code>sales</code> based on three media budgets, <code>TV</code>, <code>radio</code>, and <code>newspaper</code>.</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = sales ~ TV + radio + newspaper, data = Advertising)

Residuals:
    Min      1Q  Median      3Q     Max 
-8.8277 -0.8908  0.2418  1.1893  2.8292 

Coefficients:
             Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)  2.938889   0.311908   9.422   &lt;2e-16 ***
TV           0.045765   0.001395  32.809   &lt;2e-16 ***
radio        0.188530   0.008611  21.893   &lt;2e-16 ***
newspaper   -0.001037   0.005871  -0.177     0.86    
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 1.686 on 196 degrees of freedom
Multiple R-squared:  0.8972,    Adjusted R-squared:  0.8956 
F-statistic: 570.3 on 3 and 196 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
<ol type="a">
<li><p>Give the estimated model to predict sales.<br>
<strong>Answer</strong><br>
<span class="math inline">\(\hat{sales} = 2.938889 + (0.045765 \times\text{TV}) + (0.188530 \times\text{radio}) + (-0.001037 \times\text{newspaper})\)</span></p></li>
<li><p>Describe the null hypothesis to which the p-values given in the <code>Coefficients</code> table correspond. Explain this in terms of the <code>sales</code>, <code>TV</code>, <code>radio</code>, and <code>newspaper</code>, rather than in terms of the coefficients of the linear model.<br>
<strong>Answer</strong><br>
<span class="math inline">\(H_0\)</span>: TV is not needed in the model with the presence of radio and newspaper.<br>
<span class="math inline">\(H_0\)</span>: radio is not needed in the model with the presence of TV and newspaper.<br>
<span class="math inline">\(H_0\)</span>: newspaper is not needed in the model with the presence of TV and radio.</p></li>
<li><p>Are there any variables that may not be significant in predicting <code>sales</code>?<br>
<strong>Answer</strong><br>
Yes, newspaper may not be significant in predicting sales since its p-value is 0.86, which is greater than 0.05.</p></li>
</ol>
</section>
<section id="problem-2" class="level2">
<h2 class="anchored" data-anchor-id="problem-2">Problem 2</h2>
<p>Based on the previous problem,the following is the output from the full model: <span class="math display">\[
\text{sales} = \beta_0 + \beta_1\times\text{TV} + \beta_2\times\text{radio} + \beta_3\times\text{newspaper} + \epsilon
\]</span> </p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>Analysis of Variance Table

Response: sales
           Df Sum Sq Mean Sq   F value Pr(&gt;F)    
TV          1 3314.6  3314.6 1166.7308 &lt;2e-16 ***
radio       1 1545.6  1545.6  544.0501 &lt;2e-16 ***
newspaper   1    0.1     0.1    0.0312 0.8599    
Residuals 196  556.8     2.8                     
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
</div>
<p>Below is based on the model <span class="math display">\[
\text{sales} = \beta_0 + \beta_1\times\text{TV} + \beta_2\times\text{radio} + \epsilon
\]</span> </p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>Analysis of Variance Table

Response: sales
           Df Sum Sq Mean Sq F value    Pr(&gt;F)    
TV          1 3314.6  3314.6 1172.50 &lt; 2.2e-16 ***
radio       1 1545.6  1545.6  546.74 &lt; 2.2e-16 ***
Residuals 197  556.9     2.8                      
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
</div>
<div style="page-break-after: always;"></div>
<p>Below is based on the model <span class="math inline">\(\text{sales} = \beta_0 + \beta_1\times\text{TV} + \epsilon\)</span></p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>Analysis of Variance Table

Response: sales
           Df Sum Sq Mean Sq F value    Pr(&gt;F)    
TV          1 3314.6  3314.6  312.14 &lt; 2.2e-16 ***
Residuals 198 2102.5    10.6                      
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
</div>
<ol type="a">
<li>Determine the <code>AIC</code> for all three models.<br>
<strong>Answer</strong><br>
<code>Formula: AIC = 2(p+1) + n*ln(SSE/n)</code></li>
</ol>
<div class="cell">
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a>AIC1 <span class="ot">=</span> <span class="dv">2</span><span class="sc">*</span>(<span class="dv">4</span>) <span class="sc">+</span> <span class="dv">200</span><span class="sc">*</span><span class="fu">log</span>(<span class="fl">556.8</span><span class="sc">/</span><span class="dv">200</span>)  </span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a>AIC2 <span class="ot">=</span> <span class="dv">2</span><span class="sc">*</span>(<span class="dv">3</span>) <span class="sc">+</span> <span class="dv">200</span><span class="sc">*</span><span class="fu">log</span>(<span class="fl">556.9</span><span class="sc">/</span><span class="dv">200</span>)  </span>
<span id="cb5-3"><a href="#cb5-3" aria-hidden="true" tabindex="-1"></a>AIC3 <span class="ot">=</span> <span class="dv">2</span><span class="sc">*</span>(<span class="dv">2</span>) <span class="sc">+</span> <span class="dv">200</span><span class="sc">*</span><span class="fu">log</span>(<span class="fl">2102.5</span><span class="sc">/</span><span class="dv">200</span>)  </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p><span class="math inline">\(\text{Model 1}: \text{AIC1} = 2(3+1) + 200 \times ln(\frac{556.8}{200})\)</span> = <strong>212.7777</strong><br>
<span class="math inline">\(\text{Model 2}: \text{AIC1} = 2(2+1) + 200 \times ln(\frac{556.9}{200})\)</span> = <strong>210.8137</strong><br>
<span class="math inline">\(\text{Model 3}: \text{AIC1} = 2(1+1) + 200 \times ln(\frac{2102.5}{200})\)</span> = <strong>474.513</strong></p>
<ol start="2" type="a">
<li>Determine the <span class="math inline">\(C_p\)</span> for all three models.<br>
<strong>Answer</strong><br>
Formula: <span class="math inline">\(C_p = \frac{SSR_p}{MSE_{\text{all}}} + 2(p+1)-n\)</span></li>
</ol>
<div class="cell">
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a>Cp1 <span class="ot">=</span> <span class="fl">556.8</span><span class="sc">/</span><span class="fl">2.8</span> <span class="sc">+</span> <span class="dv">2</span><span class="sc">*</span>(<span class="dv">4</span>)<span class="sc">-</span><span class="dv">200</span>  </span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a>Cp2 <span class="ot">=</span> <span class="fl">556.9</span><span class="sc">/</span><span class="fl">2.8</span> <span class="sc">+</span> <span class="dv">2</span><span class="sc">*</span>(<span class="dv">3</span>)<span class="sc">-</span><span class="dv">200</span>  </span>
<span id="cb6-3"><a href="#cb6-3" aria-hidden="true" tabindex="-1"></a>Cp3 <span class="ot">=</span> <span class="fl">2102.5</span><span class="sc">/</span><span class="fl">2.8</span> <span class="sc">+</span> <span class="dv">2</span><span class="sc">*</span>(<span class="dv">2</span>)<span class="sc">-</span><span class="dv">200</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p><span class="math inline">\(\text{Model 1}\)</span>: <span class="math inline">\(C_p\)</span> = <span class="math inline">\(\frac{556.8}{2.8} + 2 \times (3+1) - 200\)</span> = <strong>6.857143</strong><br>
<span class="math inline">\(\text{Model 2}\)</span>: <span class="math inline">\(C_p\)</span> = <span class="math inline">\(\frac{556.9}{2.8} + 2 \times (2+1) - 200\)</span> = <strong>4.892857</strong><br>
<span class="math inline">\(\text{Model 3}\)</span>: <span class="math inline">\(C_p\)</span> = <span class="math inline">\(\frac{2102.5}{2.8} + 2 \times (1+1) - 200\)</span> = <strong>554.8929</strong></p>
<ol start="3" type="a">
<li>Determine the adjusted <span class="math inline">\(R^2\)</span> for all three models.<br>
<strong>Answer</strong><br>
Formula:<br>
<span class="math inline">\(R^2 = 1 - \frac{SSR/(n-p-1)}{TSS/(n-1)}\)</span></li>
</ol>
<div class="cell">
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a>TSS <span class="ot">=</span> <span class="fl">3314.6</span> <span class="sc">+</span> <span class="fl">1545.6</span><span class="sc">+</span> <span class="fl">0.1</span> <span class="sc">+</span> <span class="fl">556.8</span>  </span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a>R2_1 <span class="ot">=</span> <span class="dv">1</span> <span class="sc">-</span> (<span class="fl">556.8</span><span class="sc">/</span>(<span class="dv">200-3-1</span>))<span class="sc">/</span>((<span class="fl">5417.1</span>)<span class="sc">/</span>(<span class="dv">200-1</span>))  </span>
<span id="cb7-3"><a href="#cb7-3" aria-hidden="true" tabindex="-1"></a>R2_2 <span class="ot">=</span> <span class="dv">1</span> <span class="sc">-</span> (<span class="fl">556.9</span><span class="sc">/</span>(<span class="dv">200-2-1</span>))<span class="sc">/</span>((<span class="fl">5417.1</span>)<span class="sc">/</span>(<span class="dv">200-1</span>))  </span>
<span id="cb7-4"><a href="#cb7-4" aria-hidden="true" tabindex="-1"></a>R2_3 <span class="ot">=</span> <span class="dv">1</span> <span class="sc">-</span> (<span class="fl">2102.5</span><span class="sc">/</span>(<span class="dv">200-1-1</span>))<span class="sc">/</span>((<span class="fl">5417.1</span>)<span class="sc">/</span>(<span class="dv">200-1</span>))  </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>TSS = 3314.6 + 1545.6+ 0.1 + 556.8 = 5417.1<br>
<span class="math inline">\(\text{Model 1}\)</span>: <span class="math inline">\(R^2\)</span> = <span class="math inline">\(1 - \frac{556.8/(200-3-1)}{5417.1/(200-1)}\)</span> = <strong>0.8956411</strong><br>
<span class="math inline">\(\text{Model 2}\)</span>: <span class="math inline">\(R^2\)</span> = <span class="math inline">\(1 - \frac{556.9/(200-2-1)}{5417.1/(200-1)}\)</span> = <strong>0.8961522</strong><br>
<span class="math inline">\(\text{Model 3}\)</span>: <span class="math inline">\(R^2\)</span> = <span class="math inline">\(1 - \frac{2102.5/(200-1-1)}{5417.1/(200-1)}\)</span> = <strong>0.609917</strong></p>
<ol start="4" type="a">
<li>Determine the <code>RSE</code> for all three models.<br>
<strong>Answer</strong><br>
Formula: Residual Standard Error = RSE =<span class="math inline">\(\sqrt{\frac{SSR}{n-p-1}}\)</span></li>
</ol>
<div class="cell">
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a>RSE1 <span class="ot">=</span> <span class="fu">sqrt</span>(<span class="fl">556.8</span><span class="sc">/</span>(<span class="dv">200-3-1</span>))</span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a>RSE2 <span class="ot">=</span> <span class="fu">sqrt</span>(<span class="fl">556.9</span><span class="sc">/</span>(<span class="dv">200-2-1</span>))</span>
<span id="cb8-3"><a href="#cb8-3" aria-hidden="true" tabindex="-1"></a>RSE3 <span class="ot">=</span> <span class="fu">sqrt</span>(<span class="fl">2102.5</span><span class="sc">/</span>(<span class="dv">200-1-1</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p><span class="math inline">\(\text{Model 1}\)</span>: RSE =<span class="math inline">\(\sqrt{\frac{556.8}{200-3-1}}\)</span> = <strong>1.685472</strong><br>
<span class="math inline">\(\text{Model 2}\)</span>: RSE =<span class="math inline">\(\sqrt{\frac{556.9}{200-2-1}}\)</span> = <strong>1.68134</strong><br>
<span class="math inline">\(\text{Model 3}\)</span>: RSE =<span class="math inline">\(\sqrt{\frac{2102.5}{200-1-1}}\)</span> = <strong>3.258633</strong></p>
<ol start="5" type="a">
<li>Which model best fits to predict <code>sales</code> based on these statistics?<br>
<strong>Answer</strong><br>
Based on these statistics, AIC, <span class="math inline">\(C_p\)</span>, and RSE are the lowest with Model 2. <span class="math inline">\(R^2\)</span> is the highest with Model 2 as well. Therefore, Model 2 best fits to predict sales.</li>
</ol>
</section>
<section id="problem-3" class="level2">
<h2 class="anchored" data-anchor-id="problem-3">Problem 3</h2>
<p>Suppose we have a data set with five predictors, <span class="math inline">\(X_1\)</span> =GPA, <span class="math inline">\(X_2\)</span> = IQ, <span class="math inline">\(X_3\)</span> = Gender (1 for Female and 0 for Male), <span class="math inline">\(X_4\)</span> = Interaction between GPA and IQ, and <span class="math inline">\(X_5\)</span> = Interaction between GPA and Gender. The response is starting salary after graduation (in thousands of dollars). Suppose we use least squares to fit the model, and get <span class="math inline">\(\hat{\beta}_0 = 50\)</span>, <span class="math inline">\(\hat{\beta}_1 = 20\)</span>, <span class="math inline">\(\hat{\beta}_2= 0.07\)</span>, <span class="math inline">\(\hat{\beta}_3 = 35\)</span>,<span class="math inline">\(\hat{\beta}_4 = 0.01\)</span>, <span class="math inline">\(\hat{\beta}_5 = -10\)</span>.</p>
<ol type="a">
<li><p>Which answer is correct, and why?</p>
<ol type="i">
<li>For a fixed value of IQ and GPA, males earn more on average than females.<br>
</li>
<li>For a fixed value of IQ and GPA, females earn more on average than males.<br>
</li>
<li>For a fixed value of IQ and GPA, males earn more on average than females provided that the GPA is high enough.<br>
</li>
<li>For a fixed value of IQ and GPA, females earn more on average than males provided that the GPA is high enough.<br>
<strong>Answer</strong><br>
The predicted salary model:<br>
<span class="math display">\[
\hat{Salary} =
\begin{cases}
50 + (20 \times \text{GPA}) + (0.07 \times \text{IQ}) + (0.01 \times \text{GPA} \times \text{IQ}) &amp; \text{if Male} \\
85 + (10 \times \text{GPA}) + (0.07 \times \text{IQ}) + (0.01 \times \text{GPA} \times \text{IQ}) &amp; \text{if Female}
\end{cases}
\]</span> The correct answer is <strong><em>iii</em></strong> because the GPA coefficient for males is higher, so when the GPA is high enough, males will earn more on average than females. The other answers will not be correct for all cases.</li>
</ol></li>
<li><p>Predict the salary of a female with IQ of 110 and a GPA of 4.0.<br>
<strong>Answer</strong><br>
<span class="math inline">\(\hat{Salary} = 85 + (10 \times \text{4.0}) + (0.07 \times \text{110}) + (0.01 \times \text{4.0} \times \text{110}) = 137.1\)</span></p></li>
<li><p>True or false: Since the coefficient for the GPA/IQ interaction term is very small, there is very little evidence of an interaction effect. Justify your answer.<br>
<strong>Answer</strong><br>
This could be true, but we are unable to truly determine if this is true or false just by the coefficient. We need a t-test for the interaction.</p></li>
</ol>
<div style="page-break-after: always;"></div>
</section>
<section id="problem-4" class="level2">
<h2 class="anchored" data-anchor-id="problem-4">Problem 4</h2>
<p>We perform best subset, forward step-wise, and backward step-wise selection on a single data set. For each approach, we obtain <span class="math inline">\(p + 1\)</span> models, containing <span class="math inline">\(0, 1, 2,\ldots ,p\)</span> predictors. Answer true or false to the following statements.</p>
<ol type="a">
<li>The predictors in the <span class="math inline">\(k\)</span>-variable model identified by forward step-wise are a subset of the predictors in the <span class="math inline">\((k+1)\)</span>-variable model identified by forward step-wise selection. <strong>True</strong><br>
</li>
<li>The predictors in the k-variable model identified by backward step-wise are a subset of the predictors in the <span class="math inline">\((k + 1)\)</span>-variable model identified by backward step-wise selection. <strong>True</strong><br>
</li>
<li>The predictors in the <span class="math inline">\(k\)</span>-variable model identified by backward step-wise are a subset of the predictors in the <span class="math inline">\((k + 1)\)</span>-variable model identified by forward step-wise selection. <strong>False</strong><br>
</li>
<li>The predictors in the <span class="math inline">\(k\)</span>-variable model identified by forward step-wise are a subset of the predictors in the <span class="math inline">\((k+1)\)</span>-variable model identified by backward step-wise selection. <strong>False</strong><br>
</li>
<li>The predictors in the <span class="math inline">\(k\)</span>-variable model identified by best subset are a subset of the predictors in the <span class="math inline">\((k + 1)\)</span> - variable model identified by best subset selection. <strong>False</strong></li>
</ol>
</section>
<section id="problem-5" class="level2">
<h2 class="anchored" data-anchor-id="problem-5">Problem 5</h2>
<p>This question involves the use of simple linear regression on the <em>Auto</em> data set. This can be found in the <code>ISLR2</code> package in <code>R</code>.</p>
<ol type="a">
<li><p>Use the <code>lm()</code> function to perform a simple linear regression with <em>mpg</em> as the response and <em>horsepower</em> (<em>hp</em>) as the predictor. Use the <code>summary()</code> function to print the results. Comment on the output. For example:</p>
<ol type="i">
<li>Is there a relationship between the predictor and the response?<br>
</li>
<li>How strong is the relationship between the predictor and the response?<br>
</li>
<li>Is the relationship between the predictor and the response positive or negative?<br>
</li>
<li>What is the predicted mpg associated with a horsepower of 98? What are the associated 95% confidence and prediction intervals? Give an interpretation of these intervals.<br>
<strong>Answer</strong></li>
</ol></li>
</ol>
<div class="cell">
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ISLR2)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: package 'ISLR2' was built under R version 4.2.3</code></pre>
</div>
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a>auto.lm <span class="ot">=</span> <span class="fu">lm</span>(mpg <span class="sc">~</span> horsepower, <span class="at">data =</span> Auto)</span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(auto.lm)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = mpg ~ horsepower, data = Auto)

Residuals:
     Min       1Q   Median       3Q      Max 
-13.5710  -3.2592  -0.3435   2.7630  16.9240 

Coefficients:
             Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept) 39.935861   0.717499   55.66   &lt;2e-16 ***
horsepower  -0.157845   0.006446  -24.49   &lt;2e-16 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 4.906 on 390 degrees of freedom
Multiple R-squared:  0.6059,    Adjusted R-squared:  0.6049 
F-statistic: 599.7 on 1 and 390 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
<p><strong>i.</strong> With the p-value being less than 0.05, there is a relationship between horsepower(predictor) and mpg(response).</p>
<p><strong>ii.</strong> With the <span class="math inline">\(R^2\)</span> being <strong>0.6059</strong>, there is somewhat a strong relationship between horsepower and mpg.</p>
<p><strong>iii.</strong> The relationship between the predictor and the response is negative, since the coefficient for horsepower is <strong>-0.157845</strong>.</p>
<p><strong>iv.</strong></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a><span class="co"># confidence interval</span></span>
<span id="cb13-2"><a href="#cb13-2" aria-hidden="true" tabindex="-1"></a><span class="fu">predict</span>(auto.lm, <span class="fu">data.frame</span>(<span class="at">horsepower =</span> <span class="dv">98</span>), <span class="at">interval =</span> <span class="st">"confidence"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>       fit      lwr      upr
1 24.46708 23.97308 24.96108</code></pre>
</div>
</div>
<p><strong>Confidence interval</strong>: [23.97308, 24.96108], meaning that for all automobiles with a horsepower of 98, we are 95% confident that their average mpg is between 23.97308 and 24.96108.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a><span class="co"># prediction interval</span></span>
<span id="cb15-2"><a href="#cb15-2" aria-hidden="true" tabindex="-1"></a><span class="fu">predict</span>(auto.lm, <span class="fu">data.frame</span>(<span class="at">horsepower =</span> <span class="dv">98</span>), <span class="at">interval =</span> <span class="st">"prediction"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>       fit     lwr      upr
1 24.46708 14.8094 34.12476</code></pre>
</div>
</div>
<p>The predicted mpg associated with a horsepower of 98 is <strong>24.46708</strong>.<br>
<strong>Prediction interval</strong>: [14.8094, 34.12476], meaning that for one automobile with a horsepower of 98, we are 95% confident that its mpg is between 14.8094 and 34.12476.</p>
<ol start="2" type="a">
<li>Plot the response and the predictor. Use the <code>abline()</code> function to display the least squares regression line.</li>
</ol>
<div class="cell">
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a><span class="fu">attach</span>(Auto) <span class="do">##makes variables in data frame available</span></span>
<span id="cb17-2"><a href="#cb17-2" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(horsepower, mpg)</span>
<span id="cb17-3"><a href="#cb17-3" aria-hidden="true" tabindex="-1"></a><span class="fu">abline</span>(auto.lm, <span class="at">col =</span> <span class="st">"red"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="homework_2_sp24_s_files/figure-html/unnamed-chunk-12-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<ol start="3" type="a">
<li>Use the <code>plot()</code> function to produce diagnostic plots of the least squares regression fit. Comment on any problems you see with the fit.</li>
</ol>
<div class="cell">
<div class="sourceCode cell-code" id="cb18"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a><span class="fu">par</span>(<span class="at">mfrow =</span> <span class="fu">c</span>(<span class="dv">2</span>,<span class="dv">2</span>))</span>
<span id="cb18-2"><a href="#cb18-2" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(auto.lm)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="homework_2_sp24_s_files/figure-html/unnamed-chunk-13-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>There might not be a linear relationship between horsepower and mpg. There also seems to be some outliers.</p>
<div style="page-break-after: always;"></div>
</section>
<section id="problem-6" class="level2">
<h2 class="anchored" data-anchor-id="problem-6">Problem 6</h2>
<p>This question involves the use of multiple linear regression on the <em>Auto</em> data set.</p>
<ol type="a">
<li>Produce a scatterplot matrix which includes all of the variables in the data set.</li>
</ol>
<div class="cell">
<div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a><span class="fu">pairs</span>(mpg<span class="sc">~</span>., <span class="at">data =</span> Auto)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="homework_2_sp24_s_files/figure-html/unnamed-chunk-14-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<ol start="2" type="a">
<li>Compute the matrix of correlations between the variables using the function <code>cor()</code>. You will need to exclude the <code>name</code> variable, <code>cor()</code> which is qualitative.</li>
</ol>
<div class="cell">
<div class="sourceCode cell-code" id="cb20"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a><span class="fu">cor</span>(Auto[,<span class="dv">1</span><span class="sc">:</span><span class="dv">8</span>])</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>                    mpg  cylinders displacement horsepower     weight
mpg           1.0000000 -0.7776175   -0.8051269 -0.7784268 -0.8322442
cylinders    -0.7776175  1.0000000    0.9508233  0.8429834  0.8975273
displacement -0.8051269  0.9508233    1.0000000  0.8972570  0.9329944
horsepower   -0.7784268  0.8429834    0.8972570  1.0000000  0.8645377
weight       -0.8322442  0.8975273    0.9329944  0.8645377  1.0000000
acceleration  0.4233285 -0.5046834   -0.5438005 -0.6891955 -0.4168392
year          0.5805410 -0.3456474   -0.3698552 -0.4163615 -0.3091199
origin        0.5652088 -0.5689316   -0.6145351 -0.4551715 -0.5850054
             acceleration       year     origin
mpg             0.4233285  0.5805410  0.5652088
cylinders      -0.5046834 -0.3456474 -0.5689316
displacement   -0.5438005 -0.3698552 -0.6145351
horsepower     -0.6891955 -0.4163615 -0.4551715
weight         -0.4168392 -0.3091199 -0.5850054
acceleration    1.0000000  0.2903161  0.2127458
year            0.2903161  1.0000000  0.1815277
origin          0.2127458  0.1815277  1.0000000</code></pre>
</div>
</div>
<ol start="3" type="a">
<li>Use the <code>lm()</code> function to perform a multiple linear regression with <em>mpg</em> as the response and all other variables except <code>name</code> as the predictors. Use the <code>summary()</code> function to print the results. Comment on the output. For instance:
<ol type="i">
<li>Is there a relationship between the predictors and the response?<br>
</li>
<li>Which predictors appear to have a statistically significant relationship to the response?<br>
</li>
<li>What does the coefficient for the year variable suggest?</li>
</ol></li>
</ol>
<div class="cell">
<div class="sourceCode cell-code" id="cb22"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a>newAuto <span class="ot">=</span> Auto[,<span class="sc">-</span><span class="dv">9</span>] <span class="co"># takes out name variable</span></span>
<span id="cb22-2"><a href="#cb22-2" aria-hidden="true" tabindex="-1"></a>newAuto<span class="sc">$</span>origin <span class="ot">=</span> <span class="fu">as.factor</span>(newAuto<span class="sc">$</span>origin)</span>
<span id="cb22-3"><a href="#cb22-3" aria-hidden="true" tabindex="-1"></a>newAuto<span class="sc">$</span>cylinders <span class="ot">=</span> <span class="fu">as.factor</span>(newAuto<span class="sc">$</span>cylinders)</span>
<span id="cb22-4"><a href="#cb22-4" aria-hidden="true" tabindex="-1"></a>newAuto.lm <span class="ot">&lt;-</span> <span class="fu">lm</span>(mpg <span class="sc">~</span> ., <span class="at">data =</span> newAuto)</span>
<span id="cb22-5"><a href="#cb22-5" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(newAuto.lm)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = mpg ~ ., data = newAuto)

Residuals:
    Min      1Q  Median      3Q     Max 
-8.6797 -1.9373 -0.0678  1.6711 12.7756 

Coefficients:
               Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)  -2.208e+01  4.541e+00  -4.862 1.70e-06 ***
cylinders4    6.722e+00  1.654e+00   4.064 5.85e-05 ***
cylinders5    7.078e+00  2.516e+00   2.813  0.00516 ** 
cylinders6    3.351e+00  1.824e+00   1.837  0.06701 .  
cylinders8    5.099e+00  2.109e+00   2.418  0.01607 *  
displacement  1.870e-02  7.222e-03   2.590  0.00997 ** 
horsepower   -3.490e-02  1.323e-02  -2.639  0.00866 ** 
weight       -5.780e-03  6.315e-04  -9.154  &lt; 2e-16 ***
acceleration  2.598e-02  9.304e-02   0.279  0.78021    
year          7.370e-01  4.892e-02  15.064  &lt; 2e-16 ***
origin2       1.764e+00  5.513e-01   3.200  0.00149 ** 
origin3       2.617e+00  5.272e-01   4.964 1.04e-06 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 3.098 on 380 degrees of freedom
Multiple R-squared:  0.8469,    Adjusted R-squared:  0.8425 
F-statistic: 191.1 on 11 and 380 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
<p><strong>i.</strong> The p-value for the F-statistic is <span class="math inline">\(\approx\)</span> 0. Therefore, there is a relationship between the response(mpg) and at least one predictor.</p>
<p><strong>ii.</strong> By looking at the p-values from the t-test, all predictors except <strong>acceleration</strong> have a significant relationship with the response.</p>
<p><strong>iii.</strong> The coefficient for the year variable suggests that for every additional year, the mpg on average is predicted to increase by 0.737 when the other variables are fixed(coefficient of year = 0.737).</p>
<ol start="4" type="a">
<li>Use the <code>plot()</code> function to produce diagnostic plots of the linear regression fit based on the predictors that appear to have a statistically significant relationship to the response. Comment on any problems you see with the fit. Do the residual plots suggest any unusually large outliers? Does the leverage plot identify any observations with unusually high leverage?</li>
</ol>
<div class="cell">
<div class="sourceCode cell-code" id="cb24"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a>newAuto2 <span class="ot">=</span> newAuto[,<span class="sc">-</span><span class="dv">6</span>] <span class="co">#takes out acceleration from the set without name</span></span>
<span id="cb24-2"><a href="#cb24-2" aria-hidden="true" tabindex="-1"></a>newAuto2.lm <span class="ot">&lt;-</span> <span class="fu">lm</span>(mpg <span class="sc">~</span> ., <span class="at">data =</span> newAuto2)</span>
<span id="cb24-3"><a href="#cb24-3" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(newAuto2.lm)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = mpg ~ ., data = newAuto2)

Residuals:
    Min      1Q  Median      3Q     Max 
-8.7037 -1.9501 -0.0552  1.7105 12.7932 

Coefficients:
               Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)  -2.162e+01  4.231e+00  -5.111 5.09e-07 ***
cylinders4    6.784e+00  1.637e+00   4.144 4.20e-05 ***
cylinders5    7.147e+00  2.501e+00   2.857 0.004510 ** 
cylinders6    3.403e+00  1.813e+00   1.877 0.061262 .  
cylinders8    5.137e+00  2.102e+00   2.444 0.014983 *  
displacement  1.848e-02  7.169e-03   2.578 0.010312 *  
horsepower   -3.706e-02  1.071e-02  -3.459 0.000604 ***
weight       -5.696e-03  5.535e-04 -10.291  &lt; 2e-16 ***
year          7.358e-01  4.868e-02  15.114  &lt; 2e-16 ***
origin2       1.763e+00  5.506e-01   3.203 0.001476 ** 
origin3       2.621e+00  5.264e-01   4.979 9.71e-07 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 3.094 on 381 degrees of freedom
Multiple R-squared:  0.8469,    Adjusted R-squared:  0.8429 
F-statistic: 210.7 on 10 and 381 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb26"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a><span class="fu">par</span>(<span class="at">mfrow =</span> <span class="fu">c</span>(<span class="dv">2</span>,<span class="dv">2</span>))</span>
<span id="cb26-2"><a href="#cb26-2" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(newAuto2.lm)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="homework_2_sp24_s_files/figure-html/unnamed-chunk-18-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>The residuals plots suggest three possible outliers: 323, 327, and 387.<br>
The observations with high leverage: 275, 328, 387.</p>
<ol start="5" type="a">
<li>Use the * and/or : symbols to fit linear regression models with interaction effects. Do any interactions appear to be statistically significant?</li>
</ol>
<div class="cell">
<div class="sourceCode cell-code" id="cb27"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a>autoInteraction <span class="ot">=</span> <span class="fu">lm</span>(mpg <span class="sc">~</span> cylinders <span class="sc">+</span> displacement<span class="sc">:</span>horsepower <span class="sc">+</span> horsepower<span class="sc">:</span>weight <span class="sc">+</span> year <span class="sc">+</span> origin, <span class="at">data =</span> newAuto2)</span>
<span id="cb27-2"><a href="#cb27-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(autoInteraction)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = mpg ~ cylinders + displacement:horsepower + horsepower:weight + 
    year + origin, data = newAuto2)

Residuals:
    Min      1Q  Median      3Q     Max 
-9.5597 -2.1260 -0.1562  1.7374 12.6927 

Coefficients:
                          Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)             -3.054e+01  4.272e+00  -7.149 4.47e-12 ***
cylinders4               6.939e+00  1.713e+00   4.052 6.17e-05 ***
cylinders5               5.045e+00  2.598e+00   1.942 0.052885 .  
cylinders6               1.612e+00  1.773e+00   0.910 0.363644    
cylinders8               1.806e+00  1.948e+00   0.927 0.354387    
year                     7.179e-01  5.090e-02  14.104  &lt; 2e-16 ***
origin2                  2.109e+00  5.580e-01   3.781 0.000181 ***
origin3                  3.506e+00  5.186e-01   6.761 5.16e-11 ***
displacement:horsepower  2.456e-04  3.696e-05   6.643 1.06e-10 ***
horsepower:weight       -3.503e-05  3.451e-06 -10.150  &lt; 2e-16 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 3.29 on 382 degrees of freedom
Multiple R-squared:  0.8264,    Adjusted R-squared:  0.8223 
F-statistic: 202.1 on 9 and 382 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
<p>There seems to be a significant interaction for <strong>displacement:horsepower</strong> and <strong>displacement:weight</strong> when looking at those two interactions. However, when looking at these two interactions, the origin2 predictor becomes less significant.</p>
<ol start="6" type="a">
<li>Try a few different transformations of the variables, such as <em>log(X)</em>, <span class="math inline">\(\sqrt{X}\)</span>, <span class="math inline">\(X^2\)</span>. Comment on your findings.</li>
</ol>
<div class="cell">
<div class="sourceCode cell-code" id="cb29"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb29-1"><a href="#cb29-1" aria-hidden="true" tabindex="-1"></a>autot1 <span class="ot">=</span> <span class="fu">lm</span>(mpg<span class="sc">~</span> cylinders <span class="sc">+</span> <span class="fu">log</span>(displacement) <span class="sc">+</span> horsepower <span class="sc">+</span> weight <span class="sc">+</span> year <span class="sc">+</span> origin, <span class="at">data =</span> newAuto2)</span>
<span id="cb29-2"><a href="#cb29-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(autot1)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = mpg ~ cylinders + log(displacement) + horsepower + 
    weight + year + origin, data = newAuto2)

Residuals:
    Min      1Q  Median      3Q     Max 
-7.7158 -1.8949 -0.0906  1.3878 13.5460 

Coefficients:
                    Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)       -6.1463767  7.0354137  -0.874  0.38287    
cylinders4         9.3197531  1.7095745   5.452 8.99e-08 ***
cylinders5        10.6971256  2.5956770   4.121 4.63e-05 ***
cylinders6         8.3122464  2.0113842   4.133 4.41e-05 ***
cylinders8        11.5377261  2.1942982   5.258 2.43e-07 ***
log(displacement) -4.0586228  1.4932563  -2.718  0.00687 ** 
horsepower        -0.0159823  0.0103096  -1.550  0.12191    
weight            -0.0042199  0.0005974  -7.063 7.77e-12 ***
year               0.7191391  0.0483628  14.870  &lt; 2e-16 ***
origin2            0.5469506  0.5833981   0.938  0.34908    
origin3            1.4875607  0.5682270   2.618  0.00920 ** 
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 3.091 on 381 degrees of freedom
Multiple R-squared:  0.8472,    Adjusted R-squared:  0.8432 
F-statistic: 211.2 on 10 and 381 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
<p><span class="math inline">\(\log\)</span>(displacement) and mpg have a significant relationship, while horsepower and origin2 loses its significant relationship with mpg.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb31"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb31-1"><a href="#cb31-1" aria-hidden="true" tabindex="-1"></a>autot2 <span class="ot">=</span> <span class="fu">lm</span>(mpg <span class="sc">~</span> cylinders <span class="sc">+</span> displacement <span class="sc">+</span> <span class="fu">sqrt</span>(horsepower) <span class="sc">+</span> weight <span class="sc">+</span> year <span class="sc">+</span> origin, <span class="at">data =</span> newAuto2)</span>
<span id="cb31-2"><a href="#cb31-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(autot2)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = mpg ~ cylinders + displacement + sqrt(horsepower) + 
    weight + year + origin, data = newAuto2)

Residuals:
    Min      1Q  Median      3Q     Max 
-8.4243 -1.8884 -0.1068  1.6340 12.5573 

Coefficients:
                   Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)      -1.431e+01  4.610e+00  -3.105 0.002047 ** 
cylinders4        6.334e+00  1.614e+00   3.925 0.000103 ***
cylinders5        6.525e+00  2.463e+00   2.649 0.008407 ** 
cylinders6        2.990e+00  1.776e+00   1.683 0.093107 .  
cylinders8        4.839e+00  2.064e+00   2.344 0.019589 *  
displacement      1.991e-02  6.831e-03   2.914 0.003778 ** 
sqrt(horsepower) -1.107e+00  2.230e-01  -4.965 1.04e-06 ***
weight           -5.341e-03  5.538e-04  -9.645  &lt; 2e-16 ***
year              7.228e-01  4.787e-02  15.100  &lt; 2e-16 ***
origin2           1.742e+00  5.393e-01   3.231 0.001342 ** 
origin3           2.676e+00  5.141e-01   5.206 3.16e-07 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 3.045 on 381 degrees of freedom
Multiple R-squared:  0.8517,    Adjusted R-squared:  0.8478 
F-statistic: 218.8 on 10 and 381 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
<p><span class="math inline">\(\sqrt{horsepower}\)</span> and mpg have a very significant relationship.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb33"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb33-1"><a href="#cb33-1" aria-hidden="true" tabindex="-1"></a>autot3 <span class="ot">=</span> <span class="fu">lm</span>(mpg<span class="sc">~</span> cylinders <span class="sc">+</span> displacement <span class="sc">+</span> horsepower<span class="sc">:</span>weight<span class="sc">^</span><span class="dv">2</span> <span class="sc">+</span> year <span class="sc">+</span> origin, <span class="at">data =</span> newAuto2)</span>
<span id="cb33-2"><a href="#cb33-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(autot3)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = mpg ~ cylinders + displacement + horsepower:weight^2 + 
    year + origin, data = newAuto2)

Residuals:
    Min      1Q  Median      3Q     Max 
-9.5915 -2.1630 -0.3024  1.9018 13.4773 

Coefficients:
                    Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)       -2.900e+01  4.551e+00  -6.374 5.32e-10 ***
cylinders4         8.711e+00  1.819e+00   4.788 2.42e-06 ***
cylinders5         6.779e+00  2.793e+00   2.427   0.0157 *  
cylinders6         3.818e+00  2.031e+00   1.880   0.0609 .  
cylinders8         5.755e+00  2.353e+00   2.446   0.0149 *  
displacement      -3.878e-03  8.068e-03  -0.481   0.6311    
year               6.638e-01  5.319e-02  12.480  &lt; 2e-16 ***
origin2            1.383e+00  6.211e-01   2.226   0.0266 *  
origin3            3.184e+00  5.883e-01   5.413 1.10e-07 ***
horsepower:weight -1.446e-05  2.524e-06  -5.730 2.04e-08 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 3.474 on 382 degrees of freedom
Multiple R-squared:  0.8065,    Adjusted R-squared:  0.8019 
F-statistic: 176.9 on 9 and 382 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
<p>The interaction between horsepower and <span class="math inline">\(weight^2\)</span> and mpg have a significant relationship, <span class="math inline">\(\approx\)</span> 0</p>
</section>
<section id="problem-7" class="level2">
<h2 class="anchored" data-anchor-id="problem-7">Problem 7</h2>
<p>This problem involves the <code>Carseats</code> data set, from the <code>ISLR2</code> package.</p>
<ol type="a">
<li>Fit a multiple regression model to predict <code>Sales</code> using <code>Price</code>, <code>Urban</code>, and <code>US</code>.</li>
</ol>
<div class="cell">
<div class="sourceCode cell-code" id="cb35"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb35-1"><a href="#cb35-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ISLR2)</span>
<span id="cb35-2"><a href="#cb35-2" aria-hidden="true" tabindex="-1"></a>carseats.lm <span class="ot">=</span> <span class="fu">lm</span>(Sales <span class="sc">~</span> Price <span class="sc">+</span> Urban <span class="sc">+</span> US, <span class="at">data =</span> Carseats)</span>
<span id="cb35-3"><a href="#cb35-3" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(carseats.lm)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = Sales ~ Price + Urban + US, data = Carseats)

Residuals:
    Min      1Q  Median      3Q     Max 
-6.9206 -1.6220 -0.0564  1.5786  7.0581 

Coefficients:
             Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept) 13.043469   0.651012  20.036  &lt; 2e-16 ***
Price       -0.054459   0.005242 -10.389  &lt; 2e-16 ***
UrbanYes    -0.021916   0.271650  -0.081    0.936    
USYes        1.200573   0.259042   4.635 4.86e-06 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 2.472 on 396 degrees of freedom
Multiple R-squared:  0.2393,    Adjusted R-squared:  0.2335 
F-statistic: 41.52 on 3 and 396 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
<ol start="2" type="a">
<li>Provide an interpretation of each coefficient in the model. Be careful—some of the variables in the model are qualitative!<br>
<strong>Answer</strong></li>
</ol>
<p><span class="math inline">\(\beta_0\)</span> = 13.043469 - Is the starting value for Unit sales at each location.</p>
<p><span class="math inline">\(\beta_1\)</span> = -0.054459 - For each unit increase in the price for cars seats, the unit sales will decrease on average by 0.054459 thousands of dollars with a fixed value of Urban and US.</p>
<p><span class="math inline">\(\beta_2\)</span> = -0.021916 - If a store is in an urban location, the unit sales will decrease on average by 0.021916 thousands of dollars, with a fixed value of price and US.</p>
<p><span class="math inline">\(\beta_3\)</span> = 1.200573 - If a store is in ths US, the unit sales will increase on average by 1.200573 thousands of dollars, with a fixed value of price and Urban.</p>
<ol start="3" type="a">
<li><p>Write out the model in equation form, being careful to handle the qualitative variables properly.<br>
<span class="math display">\[
\hat{Sales} =
\begin{cases}
13.043469 - 0.054459 \times \text{price} &amp; \text{if rural location and not in US} \\
13.021553 - 0.054459 \times \text{price} &amp; \text{if urban location and not in US} \\
14.244042 - 0.054459 \times \text{price} &amp; \text{if rural location and in US} \\
14.222126 - 0.054459 \times \text{price} &amp; \text{if urban location and in US}
\end{cases}
\]</span></p></li>
<li><p>For which of the predictors can you reject the null hypothesis <span class="math inline">\(H_0 : \beta_j = 0\)</span>?<br>
<strong>Answer</strong><br>
Price and USYes based on their low p-value of the F-statistic.</p></li>
<li><p>On the basis of your response to the previous question, fit a smaller model that only uses the predictors for which there is evidence of association with the outcome.</p></li>
</ol>
<div class="cell">
<div class="sourceCode cell-code" id="cb37"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb37-1"><a href="#cb37-1" aria-hidden="true" tabindex="-1"></a>carseats1.lm <span class="ot">=</span> <span class="fu">lm</span>(Sales <span class="sc">~</span> Price <span class="sc">+</span> US, <span class="at">data =</span> Carseats)</span>
<span id="cb37-2"><a href="#cb37-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(carseats1.lm)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = Sales ~ Price + US, data = Carseats)

Residuals:
    Min      1Q  Median      3Q     Max 
-6.9269 -1.6286 -0.0574  1.5766  7.0515 

Coefficients:
            Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept) 13.03079    0.63098  20.652  &lt; 2e-16 ***
Price       -0.05448    0.00523 -10.416  &lt; 2e-16 ***
USYes        1.19964    0.25846   4.641 4.71e-06 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 2.469 on 397 degrees of freedom
Multiple R-squared:  0.2393,    Adjusted R-squared:  0.2354 
F-statistic: 62.43 on 2 and 397 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
<ol start="6" type="a">
<li><p>How well do the models in (a) and (e) fit the data?<br>
<strong>Answer</strong><br>
Based on models (a) and (e), the residual standard error (RSE) and adjusted R-squared values suggest that both models fit the data similarly, with model (e) fitting the data slightly better. However, neither is a good fit for their respective models due to the low adjusted R-squared value.</p></li>
<li><p>Using the model from (e), obtain 95% confidence intervals for the coefficient(s).</p></li>
</ol>
<div class="cell">
<div class="sourceCode cell-code" id="cb39"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb39-1"><a href="#cb39-1" aria-hidden="true" tabindex="-1"></a><span class="fu">confint</span>(carseats1.lm)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>                  2.5 %      97.5 %
(Intercept) 11.79032020 14.27126531
Price       -0.06475984 -0.04419543
USYes        0.69151957  1.70776632</code></pre>
</div>
</div>
<ol start="8" type="a">
<li>Is there evidence of outliers or high leverage observations in the model from (e)?</li>
</ol>
<div class="cell">
<div class="sourceCode cell-code" id="cb41"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb41-1"><a href="#cb41-1" aria-hidden="true" tabindex="-1"></a><span class="fu">par</span>(<span class="at">mfrow =</span> <span class="fu">c</span>(<span class="dv">2</span>,<span class="dv">2</span>))</span>
<span id="cb41-2"><a href="#cb41-2" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(carseats1.lm)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="homework_2_sp24_s_files/figure-html/unnamed-chunk-26-1.png" class="img-fluid" width="672"></p>
</div>
<div class="sourceCode cell-code" id="cb42"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb42-1"><a href="#cb42-1" aria-hidden="true" tabindex="-1"></a><span class="fu">which.max</span>(<span class="fu">hatvalues</span>(carseats1.lm))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>43 
43 </code></pre>
</div>
</div>
<p>There appears to be no outliers, but there is a high leverage for observation 43.</p>
</section>
<section id="problem-8" class="level2">
<h2 class="anchored" data-anchor-id="problem-8">Problem 8</h2>
<p>This problem focuses on the <strong>collinearity</strong> problem.</p>
<ol type="a">
<li>Perform the following commands in R:</li>
</ol>
<div class="cell">
<div class="sourceCode cell-code" id="cb44"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb44-1"><a href="#cb44-1" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span> (<span class="dv">1</span>)</span>
<span id="cb44-2"><a href="#cb44-2" aria-hidden="true" tabindex="-1"></a>x1<span class="ot">=</span><span class="fu">runif</span> (<span class="dv">100</span>)</span>
<span id="cb44-3"><a href="#cb44-3" aria-hidden="true" tabindex="-1"></a>x2 <span class="ot">=</span><span class="fl">0.5</span><span class="sc">*</span> x1<span class="sc">+</span><span class="fu">rnorm</span> (<span class="dv">100</span>) <span class="sc">/</span><span class="dv">10</span></span>
<span id="cb44-4"><a href="#cb44-4" aria-hidden="true" tabindex="-1"></a>y<span class="ot">=</span><span class="dv">2</span><span class="sc">+</span><span class="dv">2</span><span class="sc">*</span> x1 <span class="sc">+</span><span class="fl">0.3</span><span class="sc">*</span> x2<span class="sc">+</span><span class="fu">rnorm</span> (<span class="dv">100</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>The last line corresponds to creating a linear model in which <span class="math inline">\(y\)</span> is a function of <span class="math inline">\(x_1\)</span> and <span class="math inline">\(x_2\)</span>. Write out the form of the linear model. What are the regression coefficients?<br>
<strong>Answer</strong><br>
Linear Model Form: <span class="math inline">\(y\)</span> = <span class="math inline">\(\beta_0\)</span> + <span class="math inline">\(\beta_1\)</span><span class="math inline">\(x_1\)</span> + <span class="math inline">\(\beta_2\)</span><span class="math inline">\(x_2\)</span> + <span class="math inline">\(\epsilon\)</span><br>
Regression Coefficients: <span class="math inline">\(\beta_0\)</span> = 2, <span class="math inline">\(\beta_1\)</span> = 2, <span class="math inline">\(\beta_2\)</span> = 0.3</p>
<ol start="2" type="a">
<li>What is the correlation between <span class="math inline">\(x_1\)</span> and <span class="math inline">\(x_2\)</span>? Create a scatterplot displaying the relationship between the variables.<br>
<strong>Answer</strong></li>
</ol>
<div class="cell">
<div class="sourceCode cell-code" id="cb45"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb45-1"><a href="#cb45-1" aria-hidden="true" tabindex="-1"></a><span class="fu">cor</span>(x1, x2)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.8351212</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb47"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb47-1"><a href="#cb47-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(x1, x2) <span class="co">#scatter plot</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="homework_2_sp24_s_files/figure-html/unnamed-chunk-29-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<ol start="3" type="a">
<li>Using this data, fit a least squares regression to predict y using <span class="math inline">\(x_1\)</span> and <span class="math inline">\(x_2\)</span>. Describe the results obtained. What are <span class="math inline">\(\hat{\beta}_0\)</span>, <span class="math inline">\(\hat{\beta}_1\)</span>, and <span class="math inline">\(\hat{\beta}_2\)</span>? How do these relate to the true <span class="math inline">\(\beta_0\)</span>, <span class="math inline">\(\beta_1\)</span>, and <span class="math inline">\(\beta_2\)</span>? Can you reject the null hypothesis <span class="math inline">\(H_0 : \beta_1 = 0\)</span>? How about the null hypothesis <span class="math inline">\(H_0 : \beta_2 = 0\)</span>?<br>
<strong>Answer</strong></li>
</ol>
<div class="cell">
<div class="sourceCode cell-code" id="cb48"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb48-1"><a href="#cb48-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(<span class="fu">lm</span>(y <span class="sc">~</span> x1 <span class="sc">+</span> x2))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = y ~ x1 + x2)

Residuals:
    Min      1Q  Median      3Q     Max 
-2.8311 -0.7273 -0.0537  0.6338  2.3359 

Coefficients:
            Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)   2.1305     0.2319   9.188 7.61e-15 ***
x1            1.4396     0.7212   1.996   0.0487 *  
x2            1.0097     1.1337   0.891   0.3754    
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 1.056 on 97 degrees of freedom
Multiple R-squared:  0.2088,    Adjusted R-squared:  0.1925 
F-statistic:  12.8 on 2 and 97 DF,  p-value: 1.164e-05</code></pre>
</div>
</div>
<p>Looking at the summary, it seems that our p-value for our F-statistic is <span class="math inline">\(\approx\)</span> 0. Therefore, at least one of our predictors (<span class="math inline">\(x_1\)</span>, <span class="math inline">\(x_2\)</span>) is statistically significant for <span class="math inline">\(y\)</span>.<br>
<span class="math inline">\(\beta_0\)</span> = 2.1305<br>
<span class="math inline">\(\beta_1\)</span> = 1.4396<br>
<span class="math inline">\(\beta_2\)</span> = 1.0097</p>
<p>The estimate for <span class="math inline">\(\beta_0\)</span> is close to the true <span class="math inline">\(\beta_0\)</span>, and the estimate for <span class="math inline">\(\beta_1\)</span> is somewhat close to the true <span class="math inline">\(\beta_1\)</span>. However, the estimate for <span class="math inline">\(\beta_2\)</span> is not close to the true <span class="math inline">\(\beta_2\)</span>.<br>
We can reject the null hypothesis, with p-value = 0.0487, <span class="math inline">\(H_0\)</span>: <span class="math inline">\(\beta_1\)</span> = 0, but we fail to reject the null hypothesis, with p-value = 0.3754, <span class="math inline">\(H_0\)</span>: <span class="math inline">\(\beta_2\)</span> = 0.</p>
<ol start="4" type="a">
<li>Now fit a least squares regression to predict <span class="math inline">\(y\)</span> using only <span class="math inline">\(x_1\)</span>. Comment on your results. Can you reject the null hypothesis <span class="math inline">\(H_0 : \beta_1 = 0\)</span>?</li>
</ol>
<div class="cell">
<div class="sourceCode cell-code" id="cb50"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb50-1"><a href="#cb50-1" aria-hidden="true" tabindex="-1"></a>x1.lm <span class="ot">=</span> <span class="fu">lm</span>(y<span class="sc">~</span>x1)</span>
<span id="cb50-2"><a href="#cb50-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(x1.lm)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = y ~ x1)

Residuals:
     Min       1Q   Median       3Q      Max 
-2.89495 -0.66874 -0.07785  0.59221  2.45560 

Coefficients:
            Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)   2.1124     0.2307   9.155 8.27e-15 ***
x1            1.9759     0.3963   4.986 2.66e-06 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 1.055 on 98 degrees of freedom
Multiple R-squared:  0.2024,    Adjusted R-squared:  0.1942 
F-statistic: 24.86 on 1 and 98 DF,  p-value: 2.661e-06</code></pre>
</div>
</div>
<p>Yes, you can reject the null hypothesis <span class="math inline">\(H_0: \beta_1\)</span> = 0.<br>
The estimate coefficients are very close to the true coefficient values.</p>
<ol start="5" type="a">
<li>Now fit a least squares regression to predict <span class="math inline">\(y\)</span> using only <span class="math inline">\(x_2\)</span>. Comment on your results. Can you reject the null hypothesis <span class="math inline">\(H_0 : \beta_1 = 0\)</span>?</li>
</ol>
<div class="cell">
<div class="sourceCode cell-code" id="cb52"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb52-1"><a href="#cb52-1" aria-hidden="true" tabindex="-1"></a>x2.lm <span class="ot">=</span> <span class="fu">lm</span>(y<span class="sc">~</span>x2)</span>
<span id="cb52-2"><a href="#cb52-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(x2.lm)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = y ~ x2)

Residuals:
     Min       1Q   Median       3Q      Max 
-2.62687 -0.75156 -0.03598  0.72383  2.44890 

Coefficients:
            Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)   2.3899     0.1949   12.26  &lt; 2e-16 ***
x2            2.8996     0.6330    4.58 1.37e-05 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 1.072 on 98 degrees of freedom
Multiple R-squared:  0.1763,    Adjusted R-squared:  0.1679 
F-statistic: 20.98 on 1 and 98 DF,  p-value: 1.366e-05</code></pre>
</div>
</div>
<p>Yes, we can reject the null hypothesis <span class="math inline">\(H_0: \beta_2 = 0\)</span>.<br>
The intercept coefficient is similar to the true intercept, but the estimated <span class="math inline">\(\beta_2\)</span> is very different from the true <span class="math inline">\(\beta_2\)</span>.</p>
<ol start="6" type="a">
<li><p>Do the results obtained in (c)–(e) contradict each other? Explain your answer.<br>
<strong>Answer</strong><br>
(c)–(e) do not contradict each other, because (c) measures x2 given that x1 is fixed, and vice versa, while (d) and (e) measure x1 and x2 by themselves. (c) says that when x1 is used to predict <span class="math inline">\(y\)</span>, x2 won’t be needed. (d) and (e) state that x1 by itself is needed, and x2 by itself is needed.</p></li>
<li><p>Now suppose we obtain one additional observation, which was unfortunately miss-measured.</p></li>
</ol>
<div class="cell">
<div class="sourceCode cell-code" id="cb54"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb54-1"><a href="#cb54-1" aria-hidden="true" tabindex="-1"></a>x1<span class="ot">=</span><span class="fu">c</span>(x1 , <span class="fl">0.1</span>)</span>
<span id="cb54-2"><a href="#cb54-2" aria-hidden="true" tabindex="-1"></a>x2<span class="ot">=</span><span class="fu">c</span>(x2 , <span class="fl">0.8</span>)</span>
<span id="cb54-3"><a href="#cb54-3" aria-hidden="true" tabindex="-1"></a>y<span class="ot">=</span><span class="fu">c</span>(y,<span class="dv">6</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Re-fit the linear models from (c) to (e) using this new data. What effect does this new observation have on the each of the models? In each model, is this observation an outlier? A high-leverage point? Both? Explain your answers.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb55"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb55-1"><a href="#cb55-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(<span class="fu">lm</span>(y <span class="sc">~</span> x1 <span class="sc">+</span> x2))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = y ~ x1 + x2)

Residuals:
     Min       1Q   Median       3Q      Max 
-2.73348 -0.69318 -0.05263  0.66385  2.30619 

Coefficients:
            Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)   2.2267     0.2314   9.624 7.91e-16 ***
x1            0.5394     0.5922   0.911  0.36458    
x2            2.5146     0.8977   2.801  0.00614 ** 
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 1.075 on 98 degrees of freedom
Multiple R-squared:  0.2188,    Adjusted R-squared:  0.2029 
F-statistic: 13.72 on 2 and 98 DF,  p-value: 5.564e-06</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb57"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb57-1"><a href="#cb57-1" aria-hidden="true" tabindex="-1"></a>x1_2.lm <span class="ot">=</span> <span class="fu">lm</span>(y <span class="sc">~</span> x1)</span>
<span id="cb57-2"><a href="#cb57-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(x1_2.lm)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = y ~ x1)

Residuals:
    Min      1Q  Median      3Q     Max 
-2.8897 -0.6556 -0.0909  0.5682  3.5665 

Coefficients:
            Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)   2.2569     0.2390   9.445 1.78e-15 ***
x1            1.7657     0.4124   4.282 4.29e-05 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 1.111 on 99 degrees of freedom
Multiple R-squared:  0.1562,    Adjusted R-squared:  0.1477 
F-statistic: 18.33 on 1 and 99 DF,  p-value: 4.295e-05</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb59"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb59-1"><a href="#cb59-1" aria-hidden="true" tabindex="-1"></a>x2_2.lm <span class="ot">=</span> <span class="fu">lm</span>(y <span class="sc">~</span> x2)</span>
<span id="cb59-2"><a href="#cb59-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(x2_2.lm)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = y ~ x2)

Residuals:
     Min       1Q   Median       3Q      Max 
-2.64729 -0.71021 -0.06899  0.72699  2.38074 

Coefficients:
            Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)   2.3451     0.1912  12.264  &lt; 2e-16 ***
x2            3.1190     0.6040   5.164 1.25e-06 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 1.074 on 99 degrees of freedom
Multiple R-squared:  0.2122,    Adjusted R-squared:  0.2042 
F-statistic: 26.66 on 1 and 99 DF,  p-value: 1.253e-06</code></pre>
</div>
</div>
<p>This observation changes the coefficients for <span class="math inline">\(\beta_1\)</span> and <span class="math inline">\(\beta_2\)</span>. This is especially noticeable when looking at the regression fit that includes both predictors.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb61"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb61-1"><a href="#cb61-1" aria-hidden="true" tabindex="-1"></a><span class="fu">par</span>(<span class="at">mfrow =</span> <span class="fu">c</span>(<span class="dv">2</span>,<span class="dv">2</span>))</span>
<span id="cb61-2"><a href="#cb61-2" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(<span class="fu">lm</span>(y <span class="sc">~</span> x1 <span class="sc">+</span> x2))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="homework_2_sp24_s_files/figure-html/unnamed-chunk-37-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb62"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb62-1"><a href="#cb62-1" aria-hidden="true" tabindex="-1"></a><span class="fu">par</span>(<span class="at">mfrow =</span> <span class="fu">c</span>(<span class="dv">2</span>,<span class="dv">2</span>))</span>
<span id="cb62-2"><a href="#cb62-2" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(x1_2.lm)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="homework_2_sp24_s_files/figure-html/unnamed-chunk-38-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb63"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb63-1"><a href="#cb63-1" aria-hidden="true" tabindex="-1"></a><span class="fu">par</span>(<span class="at">mfrow =</span> <span class="fu">c</span>(<span class="dv">2</span>,<span class="dv">2</span>))</span>
<span id="cb63-2"><a href="#cb63-2" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(x2_2.lm)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="homework_2_sp24_s_files/figure-html/unnamed-chunk-39-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>The extra observation 101 is not an outlier, but it does have high leverage. </p>
</section>
<section id="problem-9" class="level2">
<h2 class="anchored" data-anchor-id="problem-9">Problem 9</h2>
<p>In this exercise, we will generate simulated data, and will then use this data to perform best subset selection.</p>
<ol type="a">
<li>Use the <code>rnorm()</code> function to generate a predictor <span class="math inline">\(X\)</span> of length <span class="math inline">\(n\)</span> = 100, as well as a noise vector <span class="math inline">\(\epsilon\)</span> of length <span class="math inline">\(n\)</span> = 100.</li>
</ol>
<div class="cell">
<div class="sourceCode cell-code" id="cb64"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb64-1"><a href="#cb64-1" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">1</span>)</span>
<span id="cb64-2"><a href="#cb64-2" aria-hidden="true" tabindex="-1"></a>X <span class="ot">=</span> <span class="fu">rnorm</span>(<span class="dv">100</span>)</span>
<span id="cb64-3"><a href="#cb64-3" aria-hidden="true" tabindex="-1"></a>e <span class="ot">=</span> <span class="fu">rnorm</span>(<span class="dv">100</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<ol start="2" type="a">
<li>Generate a response vector <span class="math inline">\(Y\)</span> of length n = 100 according to the model <span class="math display">\[
Y = \beta_0 + \beta_1X + \beta_2X^2 + \beta_3X^3 + \epsilon,
\]</span> where <span class="math inline">\(\beta_0\)</span>, <span class="math inline">\(\beta_1\)</span>, <span class="math inline">\(\beta_2\)</span>, and <span class="math inline">\(\beta_3\)</span> are constants of your choice.<br>
<strong>Answer</strong></li>
</ol>
<div class="cell">
<div class="sourceCode cell-code" id="cb65"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb65-1"><a href="#cb65-1" aria-hidden="true" tabindex="-1"></a>Y <span class="ot">=</span> <span class="dv">4</span> <span class="sc">+</span> <span class="sc">-</span><span class="fl">0.5</span><span class="sc">*</span>X <span class="sc">+</span> <span class="fl">0.3</span><span class="sc">*</span>X<span class="sc">^</span><span class="dv">2</span> <span class="sc">+</span> <span class="dv">2</span><span class="sc">*</span>X<span class="sc">^</span><span class="dv">3</span> <span class="sc">+</span> e</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Where <span class="math inline">\(\beta_0\)</span> = 4, <span class="math inline">\(\beta_1\)</span> = -0.5, <span class="math inline">\(\beta_2\)</span> = 0.3, and <span class="math inline">\(\beta_3\)</span> = 2</p>
<ol start="3" type="a">
<li>Use the <code>regsubsets()</code> function to perform best subset selection in order to choose the best model containing the predictors <span class="math inline">\(X,X^2,\ldots,X^{10}\)</span>. What is the best model obtained according to <span class="math inline">\(C_p\)</span>, BIC, and adjusted <span class="math inline">\(R^2\)</span>? Show some plots to provide evidence for your answer, and report the coefficients of the best model obtained. Note you will need to use the <code>data.frame()</code> function to create a single data set containing both <span class="math inline">\(X\)</span> and <span class="math inline">\(Y\)</span>.</li>
</ol>
<div class="cell">
<div class="sourceCode cell-code" id="cb66"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb66-1"><a href="#cb66-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(leaps)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: package 'leaps' was built under R version 4.2.3</code></pre>
</div>
<div class="sourceCode cell-code" id="cb68"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb68-1"><a href="#cb68-1" aria-hidden="true" tabindex="-1"></a>qNine <span class="ot">=</span> <span class="fu">data.frame</span>(<span class="fu">cbind</span>(Y,X))</span>
<span id="cb68-2"><a href="#cb68-2" aria-hidden="true" tabindex="-1"></a>nine.fit <span class="ot">=</span> <span class="fu">regsubsets</span>(Y <span class="sc">~</span> <span class="fu">poly</span>(X,<span class="dv">10</span>), <span class="at">data =</span> qNine)</span>
<span id="cb68-3"><a href="#cb68-3" aria-hidden="true" tabindex="-1"></a>nine.res <span class="ot">=</span> <span class="fu">summary</span>(nine.fit)</span>
<span id="cb68-4"><a href="#cb68-4" aria-hidden="true" tabindex="-1"></a>nine.res</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Subset selection object
Call: regsubsets.formula(Y ~ poly(X, 10), data = qNine)
10 Variables  (and intercept)
              Forced in Forced out
poly(X, 10)1      FALSE      FALSE
poly(X, 10)2      FALSE      FALSE
poly(X, 10)3      FALSE      FALSE
poly(X, 10)4      FALSE      FALSE
poly(X, 10)5      FALSE      FALSE
poly(X, 10)6      FALSE      FALSE
poly(X, 10)7      FALSE      FALSE
poly(X, 10)8      FALSE      FALSE
poly(X, 10)9      FALSE      FALSE
poly(X, 10)10     FALSE      FALSE
1 subsets of each size up to 8
Selection Algorithm: exhaustive
         poly(X, 10)1 poly(X, 10)2 poly(X, 10)3 poly(X, 10)4 poly(X, 10)5
1  ( 1 ) "*"          " "          " "          " "          " "         
2  ( 1 ) "*"          " "          "*"          " "          " "         
3  ( 1 ) "*"          "*"          "*"          " "          " "         
4  ( 1 ) "*"          "*"          "*"          " "          "*"         
5  ( 1 ) "*"          "*"          "*"          "*"          "*"         
6  ( 1 ) "*"          "*"          "*"          "*"          "*"         
7  ( 1 ) "*"          "*"          "*"          "*"          "*"         
8  ( 1 ) "*"          "*"          "*"          "*"          "*"         
         poly(X, 10)6 poly(X, 10)7 poly(X, 10)8 poly(X, 10)9 poly(X, 10)10
1  ( 1 ) " "          " "          " "          " "          " "          
2  ( 1 ) " "          " "          " "          " "          " "          
3  ( 1 ) " "          " "          " "          " "          " "          
4  ( 1 ) " "          " "          " "          " "          " "          
5  ( 1 ) " "          " "          " "          " "          " "          
6  ( 1 ) " "          " "          " "          " "          "*"          
7  ( 1 ) " "          "*"          " "          " "          "*"          
8  ( 1 ) " "          "*"          " "          "*"          "*"          </code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb70"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb70-1"><a href="#cb70-1" aria-hidden="true" tabindex="-1"></a>nineTable <span class="ot">=</span> <span class="fu">cbind</span>(nine.res<span class="sc">$</span>cp, nine.res<span class="sc">$</span>bic, nine.res<span class="sc">$</span>adjr2)</span>
<span id="cb70-2"><a href="#cb70-2" aria-hidden="true" tabindex="-1"></a><span class="fu">colnames</span>(nineTable) <span class="ot">=</span> <span class="fu">c</span>(<span class="st">"Cp"</span>, <span class="st">"BIC"</span>, <span class="st">"AdjR^2"</span>)</span>
<span id="cb70-3"><a href="#cb70-3" aria-hidden="true" tabindex="-1"></a>nineTable</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>              Cp        BIC    AdjR^2
[1,] 1037.196066  -79.59743 0.5843557
[2,]   72.900896 -266.53197 0.9381514
[3,]    2.185943 -319.13973 0.9647339
[4,]    1.866261 -317.02827 0.9652404
[5,]    2.193128 -314.26116 0.9655104
[6,]    3.235128 -310.72383 0.9655098
[7,]    5.119994 -306.24777 0.9651799
[8,]    7.027330 -301.74663 0.9648338</code></pre>
</div>
</div>
<p>Smallest <span class="math inline">\(C_p\)</span>: Subset 4<br>
Smallest BIC: Subset 3<br>
Biggest Adjusted <span class="math inline">\(R^2\)</span>: Subset 5<br>
Out of those 3 subsets, <strong>Subset 4</strong> seems to be the best choice.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb72"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb72-1"><a href="#cb72-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(<span class="fu">lm</span>(Y <span class="sc">~</span> <span class="fu">poly</span>(X,<span class="dv">4</span>), <span class="at">data =</span> qNine))<span class="sc">$</span>coef</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>             Estimate Std. Error   t value     Pr(&gt;|t|)
(Intercept)  4.572185 0.09590514 47.674034 3.810709e-68
poly(X, 4)1 39.128403 0.95905143 40.799066 5.115231e-62
poly(X, 4)2  8.287330 0.95905143  8.641174 1.319125e-13
poly(X, 4)3 30.210483 0.95905143 31.500378 4.437446e-52
poly(X, 4)4  1.257095 0.95905143  1.310769 1.930956e-01</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb74"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb74-1"><a href="#cb74-1" aria-hidden="true" tabindex="-1"></a><span class="fu">par</span>(<span class="at">mfrow =</span> <span class="fu">c</span>(<span class="dv">2</span>,<span class="dv">2</span>))</span>
<span id="cb74-2"><a href="#cb74-2" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(<span class="fu">lm</span>(Y <span class="sc">~</span> <span class="fu">poly</span>(X, <span class="dv">3</span>), <span class="at">data =</span> qNine))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="homework_2_sp24_s_files/figure-html/unnamed-chunk-45-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb75"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb75-1"><a href="#cb75-1" aria-hidden="true" tabindex="-1"></a><span class="fu">par</span>(<span class="at">mfrow =</span> <span class="fu">c</span>(<span class="dv">2</span>,<span class="dv">2</span>))</span>
<span id="cb75-2"><a href="#cb75-2" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(<span class="fu">lm</span>(Y <span class="sc">~</span> <span class="fu">poly</span>(X,<span class="dv">4</span>), <span class="at">data =</span> qNine))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="homework_2_sp24_s_files/figure-html/unnamed-chunk-46-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb76"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb76-1"><a href="#cb76-1" aria-hidden="true" tabindex="-1"></a><span class="fu">par</span>(<span class="at">mfrow =</span> <span class="fu">c</span>(<span class="dv">2</span>,<span class="dv">2</span>))</span>
<span id="cb76-2"><a href="#cb76-2" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(<span class="fu">lm</span>(Y <span class="sc">~</span> <span class="fu">poly</span>(X,<span class="dv">5</span>), <span class="at">data =</span> qNine))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="homework_2_sp24_s_files/figure-html/unnamed-chunk-47-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<ol start="4" type="a">
<li>Repeat (c), using forward step-wise selection and also using backwards step-wise selection. How does your answer compare to the results in (c)?</li>
</ol>
<div class="cell">
<div class="sourceCode cell-code" id="cb77"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb77-1"><a href="#cb77-1" aria-hidden="true" tabindex="-1"></a><span class="fu">step</span>(<span class="fu">lm</span>(Y <span class="sc">~</span> <span class="fu">poly</span>(X,<span class="dv">10</span>), <span class="at">data =</span> qNine))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Start:  AIC=4.64
Y ~ poly(X, 10)

              Df Sum of Sq     RSS    AIC
&lt;none&gt;                       84.06   4.64
- poly(X, 10) 10    2517.3 2601.34 327.86</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = Y ~ poly(X, 10), data = qNine)

Coefficients:
  (Intercept)   poly(X, 10)1   poly(X, 10)2   poly(X, 10)3   poly(X, 10)4  
       4.5722        39.1284         8.2873        30.2105         1.2571  
 poly(X, 10)5   poly(X, 10)6   poly(X, 10)7   poly(X, 10)8   poly(X, 10)9  
       1.4802         0.1190        -0.3298        -0.1079        -0.2958  
poly(X, 10)10  
      -0.9512  </code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb80"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb80-1"><a href="#cb80-1" aria-hidden="true" tabindex="-1"></a><span class="fu">step</span>(<span class="fu">lm</span>(Y <span class="sc">~</span> <span class="fu">poly</span>(X,<span class="dv">10</span>), <span class="at">data =</span> qNine), <span class="at">direction =</span> <span class="st">"forward"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Start:  AIC=4.64
Y ~ poly(X, 10)</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = Y ~ poly(X, 10), data = qNine)

Coefficients:
  (Intercept)   poly(X, 10)1   poly(X, 10)2   poly(X, 10)3   poly(X, 10)4  
       4.5722        39.1284         8.2873        30.2105         1.2571  
 poly(X, 10)5   poly(X, 10)6   poly(X, 10)7   poly(X, 10)8   poly(X, 10)9  
       1.4802         0.1190        -0.3298        -0.1079        -0.2958  
poly(X, 10)10  
      -0.9512  </code></pre>
</div>
</div>
<p>According to both stepwise selections, all predictors are needed in the regression (as no further steps were taken).</p>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->



</body></html>